### ISSUE TITLE
Update and Test Search Provider for Version 1.1.0 of On_Search Response

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#101]
### Description
Request changes for Venky's search provider to support version 1.1.0 of the on_search response. Ensure that the updated search provider is integrated and tested with the Beckn instance.

### Goals
- [ ] Request changes from Venky for supporting version 1.1.0 of on_search response.
- [ ] Integrate the updated search provider with the Beckn instance.
- [ ] Test the updated search functionality.
- [ ] Identify and resolve any issues during the update and integration process.

### Expected Outcome
Successful update, integration, and testing of Venky's search provider to support version 1.1.0 of the on_search response in the Beckn instance.

### Acceptance Criteria
- [ ] Changes requested from Venky for version 1.1.0 support.
- [ ] Updated search provider integrated with the Beckn instance.
- [ ] Updated search functionality tested and verified.
- [ ] Any issues identified and resolved.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Search Provider Integration

### Tech Skills Needed
- Integration
- Testing
- Version Control

### Complexity
Medium

### Category
Integration and Testing

### Sub Category
Search Provider

**Comment by shreyvishal** [comment]
Current Status: Have tried some prior testing on Venky's Search Provider and found that it only supported `0.9.4` and not `1.1.0` core_version. So have connected with Venky and informed him about the issue and the changes required. And he has done the changes and pushed to the respective repo.
