### ISSUE TITLE
Include New Search Gateway Image in Beckn-ONIX Script

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#104]
### Description
Ensure that the changes to the search provider are reflected on the Vistaar instance gateway. Include the newly created and published search gateway image in the Beckn-ONIX script.

### Goals
- [x] Reflect changes to the search provider on the Vistaar instance gateway.
- [x] Ensure the new search gateway image is incorporated into the Beckn-ONIX script.
- [x] Validate the Beckn-ONIX script with the new image.

### Expected Outcome
Successful integration of the new search gateway image into the Beckn-ONIX script, ensuring all changes are accurately reflected on the Vistaar instance gateway.

### Acceptance Criteria
- [x] Changes to the search provider reflected on the Vistaar gateway.
- [x] New search gateway image included in the Beckn-ONIX script.
- [x] Beckn-ONIX script validated and confirmed to work correctly with the new image.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Search Provider Integration

### Tech Skills Needed
- Docker
- Image Integration
- Script Modification
- Testing

### Complexity
Medium

### Category
Integration and Deployment

### Sub Category
Search Provider

**Comment by em-tpt-bbandi** [comment]
changed the `fidedocker/gateway:latest` to `fidedocker/gateway:searchprovider` in onix script and redeployed in vistaar environment and tested.
