### ISSUE TITLE
Deploy New Search Gateway on Vistaar Instance

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#105]
### Description
Ensure that the changes to the search provider are reflected on the Vistaar instance gateway. Deploy the new gateway/search provider on the Vistaar instance, ensuring the instance configuration meets the minimum requirements (4vCPU, 8GB RAM).

### Goals
- [ ] Reflect changes to the search provider on the Vistaar instance gateway.
- [ ] Deploy the new search gateway/search provider on the Vistaar instance.
- [ ] Ensure the instance configuration is at least 4vCPU and 8GB RAM.

### Expected Outcome
Successful deployment of the new search gateway on the Vistaar instance, with changes accurately reflected and the instance configured as required.

### Acceptance Criteria
- [ ] Changes to the search provider reflected on the Vistaar gateway.
- [ ] New search gateway deployed on the Vistaar instance.
- [ ] Instance configuration meets the minimum requirements (4vCPU, 8GB RAM).

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Search Provider Integration

### Tech Skills Needed
- Docker
- Deployment
- Instance Configuration
- Testing

### Complexity
Medium

### Category
Integration and Deployment

### Sub Category
Search Provider

**Comment by em-tpt-bbandi** [comment]
deployed  gateway:search-provider in vistaar environment and tested.
