### ISSUE TITLE
Update BPP to Incorporate New Search Provider

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#106]
### Description
Ensure that changes to the search provider are reflected on the Vistaar instance gateway. Identify and make necessary changes on the BPP side to incorporate the new search provider.

### Goals
- [ ] Reflect changes to the search provider on the Vistaar instance gateway.
- [ ] Identify required changes on the BPP side.
- [ ] Implement and test changes to incorporate the new search provider on the BPP side.

### Expected Outcome
Successful integration of the new search provider with the BPP, with changes accurately reflected on the Vistaar instance gateway.

### Acceptance Criteria
- [ ] Changes to the search provider reflected on the Vistaar gateway.
- [ ] Necessary changes identified and made on the BPP side.
- [ ] Successful integration and testing of the new search provider with the BPP.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Search Provider Integration

### Tech Skills Needed
- BPP Development
- Search Provider Integration
- Testing

### Complexity
Medium

### Category
Integration and Development

### Sub Category
Search Provider

**Comment by shreyvishal** [comment]
Current Status: Have made the changes on BPP side to send the on_search API call to Search Provider. But since the is no confirmation on going ahead with Search Provider. This task is also put on hold till further communication.
