### ISSUE TITLE
Write K6 Scripts for Multi-Domain Load Testing in Beckn

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#112]
## Description
Develop comprehensive K6 scripts for load testing Beckn components, covering multiple domains and various actions within each domain.

## Goals
- [ ] Identify key domains and actions within Beckn for load testing.
- [ ] Design and implement K6 scripts for each identified domain and action.
- [ ] Ensure scripts can simulate realistic user behavior across domains.
- [ ] Incorporate parameterization and dynamic data generation in scripts.
- [ ] Create modular and reusable script components.

## Expected Outcome
A suite of K6 scripts capable of conducting thorough load tests across multiple Beckn domains, simulating various user actions and scenarios.

## Acceptance Criteria
- [ ] K6 scripts cover at least 3 major domains within Beckn.
- [ ] Each domain has scripts for a minimum of 5 distinct actions.
- [ ] Scripts include proper error handling and logging mechanisms.
- [ ] Documentation provided for each script, explaining its purpose and usage.
- [ ] Scripts are parameterized to allow easy configuration of load patterns.
- [ ] Successful execution of scripts in a test environment, generating relevant metrics.

## Mockups / Wireframes
Not applicable

## Product Name
Beckn

## Domain
Load Testing Preparation/Approach

## Tech Skills Needed
- K6 Scripting
- JavaScript
- Performance Testing Concepts
- Beckn Architecture Understanding
- API Testing

## Complexity
High

## Category
Testing

**Comment by shreyvishal** [comment]
Current Status: Have written K6 scripts for select, init, confirm, status for 4 domains, to include the scenario of testing Protocol server on multiple domains and multiple endpoints. And have done some round of testing on the Vistaar Instances.
