### ISSUE TITLE
Develop K6 Scripts for Load Testing Beckn Registry, Gateway

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#114]
## Description
Create comprehensive K6 scripts to perform load testing on three key components of Beckn: the registry, gateway, and search provider. These scripts will help evaluate the performance and scalability of these critical components under various load conditions.

## Goals
- [ ] Analyze the API endpoints and functionalities of Beckn's registry, gateway, and search provider.
- [ ] Design and implement K6 scripts for each component, covering their primary operations.
- [ ] Incorporate realistic user scenarios and data patterns in the scripts.
- [ ] Develop parameterized scripts to allow for flexible load testing configurations.
- [ ] Implement proper error handling and result logging in the scripts.

## Expected Outcome
A set of robust K6 scripts capable of conducting thorough load tests on Beckn's registry, gateway, and search provider, providing valuable insights into their performance characteristics.

## Acceptance Criteria
- [ ] Separate K6 scripts created for registry, gateway, and search provider components.
- [ ] Each script covers at least 5 key operations or endpoints of its respective component.
- [ ] Scripts include variability in test data and user behavior to simulate real-world scenarios.
- [ ] Parameterization allows easy adjustment of virtual user counts, test duration, and other relevant factors.
- [ ] Scripts generate comprehensive performance metrics (e.g., response times, error rates, throughput).
- [ ] Documentation provided for each script, explaining its purpose, usage, and configuration options.
- [ ] Successful execution of scripts in a test environment, demonstrating their effectiveness in load testing.

## Mockups / Wireframes
Not applicable

## Product Name
Beckn

## Domain
Load Testing Preparation/Approach

## Tech Skills Needed
- K6 Scripting
- JavaScript
- Performance Testing Concepts
- Understanding of Beckn Architecture (Registry, Gateway, Search Provider)
- API Testing
- Data Generation for Test Scenarios

## Complexity
High

## Category
Testing

**Comment by shreyvishal** [comment]
Current Status: Have written some scripts incorporating the APIs communication happening on the BAP side with registry and gateway.
