### ISSUE TITLE
Kubernetes Setup for Horizontal Scaling - AWS Infrastructure Setup

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#117]
### Description
Setup AWS infrastructure including PostgreSQL and Kubernetes for horizontal scaling.

### Goals
- [ ] Launch an EC2 instance for PostgreSQL.
- [ ] Install and configure PostgreSQL for remote access and security.
- [ ] Launch two EC2 instances for Kubernetes (one master, one worker).
- [ ] Install Kubernetes on both instances and configure the cluster.
- [ ] Set up Calico for networking in the Kubernetes cluster.
- [ ] Ensure security configurations for master-worker communication.

### Expected Outcome
AWS infrastructure ready with PostgreSQL and a Kubernetes cluster configured for horizontal scaling.

### Acceptance Criteria
- [ ] PostgreSQL instance launched and accessible remotely.
- [ ] Kubernetes cluster deployed with one master and one worker node.
- [ ] Calico networking configured and operational.
- [ ] Security configurations for Kubernetes master-worker communication implemented.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Kubernetes Setup

### Tech Skills Needed
- AWS EC2
- PostgreSQL
- Kubernetes
- Calico Networking
- Security Configuration

### Complexity
High

### Category
Infrastructure

**Comment by prasad-takale-eminds** [comment]
We have created a k8s 2 cluster with 1 master and 1 worker node for BPP and BAP separately. Also, set up the MongoDB, Redis and PQ servers separately.
