### ISSUE TITLE
DevOps Setup for Vistaar Environment

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#118]
### Description
Configure DevOps setups for the following URLs in the Vistaar environment.

### Goals
- [x] Set up infrastructure for the following URLs:
  - BAP Client: [https://bap-ps-client-vistaar.becknprotocol.io](https://bap-ps-client-vistaar.becknprotocol.io)
  - BAP Network: [https://bap-ps-network-vistaar.becknprotocol.io](https://bap-ps-network-vistaar.becknprotocol.io)
  - Registry: [https://registry-vistaar.becknprotocol.io](https://registry-vistaar.becknprotocol.io)
  - Gateway: [https://gateway-vistaar.becknprotocol.io](https://gateway-vistaar.becknprotocol.io)
  - BPP Network: [https://bpp-ps-network-sandbox-vistaar.becknprotocol.io](https://bpp-ps-network-sandbox-vistaar.becknprotocol.io)
  - BPP Client: [https://bpp-ps-client-sandbox-vistaar.becknprotocol.io](https://bpp-ps-client-sandbox-vistaar.becknprotocol.io)
  - Sandbox: [https://bpp-unified-sandbox-vistaar.becknprotocol.io](https://bpp-unified-sandbox-vistaar.becknprotocol.io)

### Steps
- [x] Provision necessary infrastructure on AWS or preferred cloud provider.
- [x] Configure DNS settings and SSL certificates for each URL.
- [x] Set up monitoring and logging solutions as per project requirements.

### Expected Outcome
Fully operational URLs accessible within the Vistaar environment with proper DevOps configurations.

### Acceptance Criteria
- [x] All URLs configured and accessible.
- [x] DNS and SSL configurations verified.
- [x] Monitoring and logging tools set up and tested.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
DevOps

### Tech Skills Needed
- AWS or similar cloud infrastructure management
- DNS and SSL configuration
- Monitoring and logging tools setup

### Complexity
High

### Category
Infrastructure

**Comment by em-tpt-bbandi** [comment]
done all the dns required for vistaar and SSL cert.

![Image](https://github.com/beckn/beckn-onix/assets/126443511/717d6a35-ce27-4337-bd41-4de99795b205)
