### ISSUE TITLE
Load Testing for Beckn Application (Horizontal Scaling)

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#120]
## Description
The goal of this issue is to perform load testing on the Beckn application to assess its horizontal scalability. We'll simulate various user scenarios and analyze system performance under heavy loads.

## Goals
- Conduct load tests using appropriate tools (e.g., JMeter, Locust).
- Identify bottlenecks, response times, and resource utilization.
- Determine the system's ability to handle increased traffic.

## Expected Outcome
A comprehensive load testing report with actionable recommendations for improving scalability.

## Acceptance Criteria
- [ ] Set up load testing environment.
- [ ] Define test scenarios (e.g., concurrent users, API endpoints).
- [ ] Execute load tests.
- [ ] Analyze results and identify performance bottlenecks.

## Mockups / Wireframes
N/A 

## Product Name
Beckn

## Domain
Load Testing

## Tech Skills Needed
- Load testing tools (e.g., JMeter, Locust)
- Understanding of distributed systems
- Performance analysis

## Complexity
High

## Category
Performance Testing

## Sub Category
Horizontal Scaling

**Comment by shreyvishal** [comment]
Current Status: Have done the testing and below is the link to the recorded Metrics.

[Metrics](https://docs.google.com/spreadsheets/d/1GOnIF8bRD-LvrVvhSuqleqxg-W3NLszeAwGMRGLSM3I/edit?gid=0#gid=0)
