### ISSUE TITLE
Load Testing for Beckn Application (Vertical Scaling)

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#121]
## Description
The goal of this issue is to perform load testing on the Beckn application to assess its vertical scalability. We'll focus on evaluating the system's ability to handle increased load, on various resource configuration, such as memory, CPU, and CPU core connections.

## Goals
- Conduct vertical scalability tests (e.g., increasing server resources).
- Monitor performance metrics (e.g., response time, memory usage).
- Identify any bottlenecks related to vertical scaling.

## Expected Outcome
A comprehensive report on the application's vertical scalability, including recommendations for optimization.

## Acceptance Criteria
- [ ] Set up test environment with varying resource configurations.
- [ ] Execute vertical scalability tests.
- [ ] Monitor system performance during tests.
- [ ] Analyze results and provide insights.

## Mockups / Wireframes
N/A

## Product Name
Beckn

## Domain
Load Testing

## Tech Skills Needed
- Understanding of server resource allocation
- Performance monitoring tools
- Knowledge of vertical scaling techniques

## Complexity
Medium

## Category
Performance Testing

## Sub Category
Vertical Scaling

**Comment by shreyvishal** [comment]
Current Status: Have done the testing and below is the link to the recorded Metrics.

[Metrics](https://docs.google.com/spreadsheets/d/1xHjvjbw9ILOeLCePdCBvnivNgI6skfwH2VxW3BKgPRM/edit?usp=sharing)
