### ISSUE TITLE
Create sandbox for Vistaar

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#122]
## [Description]
Vistaar requires a sandbox environment for testing, development, and experimentation. The sandbox will provide an isolated space where changes and configurations can be tested without affecting the production environment.
Create sandbox as per this [JSONs](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/475136017/Sample+JSONs)

## Goals
- Set up a dedicated sandbox environment for Vistaar.
- Ensure that the sandbox mimics the production environment as closely as possible.
- Provide developers and testers with a safe space to experiment.

## Expected Outcome
A functional Vistaar sandbox environment with the following characteristics:
- Isolated from the production system.
- Contains necessary components (e.g., databases, services, APIs).
- Allows testing of new features, configurations, and integrations.

## Acceptance Criteria
- The sandbox environment is provisioned with the required resources.
- Developers and testers can access the sandbox.
- Changes made in the sandbox do not impact the production system.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Vistaar

## Tech Skills Needed
- Infrastructure setup (virtual machines, containers, etc.)
- Knowledge of Vistaar architecture

## Complexity
Medium

## Category
Environment Setup

## Sub Category
Sandbox Creation

**Comment by shreyvishal** [comment]
Current Status: Development is done and the sandbox is deployed in the BOC env. And the postman is also created and the testing of this Postman is also done in the BOC env. The JSON responses are also added to the artefacts folder.
PC: [Postman Collection](https://github.com/beckn/beckn-sandbox/blob/main/artefacts/Vistaar/Vistaar-Advisory.postman_collection.json)
