### ISSUE TITLE
Review and Update Vistaar Implementation Guide

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#123]
### Description
Review the Vistaar Implementation Guide to ensure it is specific to the Vistaar use case. Update the guide by adding example JSONs and making necessary adjustments. 

Onest standard implementation guide - reference
https://github.com/ONEST-Network/ONEST-Specification/tree/main/docs/implementation_guides

### Goals
- [ ] Review the current implementation guide for Vistaar.
- [ ] Ensure the content is tailored specifically for the Vistaar use case.
- [ ] Add relevant example JSONs under the appropriate sections.
- [ ] Use the ONEST implementation guide as a reference for structure and content.

### Steps
- [ ] Access the Vistaar Implementation Guide: [Vistaar Implementation Guide] (https://docs.google.com/document/d/1KwLAmr3-98NfWtVcCNsCqCuLj0AnGTaLFLl6HjS1VkU/edit)
- [ ] Read through the entire document to understand the current content.
- [ ] Compare with the ONEST implementation guide for format and content.
- [ ] Make necessary changes to ensure the guide is specific to Vistaar.
- [ ] Add example JSONs under the relevant sections to provide clarity.

### Expected Outcome
An updated and comprehensive Vistaar Implementation Guide with clear, specific content and example JSONs.

### Acceptance Criteria
- [ ] All content reviewed and adjusted to be specific to Vistaar.
- [ ] Example JSONs added under the relevant sections.
- [ ] Guide structure aligned with the ONEST implementation guide where applicable.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn/Vistaar

### Domain
Documentation

### Tech Skills Needed
- Understanding of implementation guides
- Familiarity with JSON formatting
- Attention to detail for reviewing and updating documentation

### Complexity
Medium

### Category
Documentation

**Comment by rajaneeshk90** [comment]
Reviewed the implementation guide: https://docs.google.com/document/d/1KwLAmr3-98NfWtVcCNsCqCuLj0AnGTaLFLl6HjS1VkU/edit (example JSON, Beckn Schema, arch diagrams)

<img width="694" alt="masterdiag" src="https://github.com/user-attachments/assets/c481dc25-1623-46bc-bdd3-507b2d0470d4">
