### ISSUE TITLE
K8s setup for Protocol Server BPP

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#129]
### Title:
K8s setup for Protocol Server BPP

### Description:
Setup K8s cluster with 1 master and 1 worker node for BPP Protocol Server.

### Goals:
- [ ] Create a Kubernetes cluster.
- [ ] Configure one master node.
- [ ] Configure one worker node.
- [ ] Ensure proper network and security configurations.

### Expected Outcome:
A fully functional Kubernetes cluster for the BPP Protocol Server with one master and one worker node.

### Acceptance Criteria:
- [ ] Kubernetes cluster is set up with one master and one worker node.
- [ ] BPP Protocol Server is deployed and running smoothly on the cluster.
- [ ] Network and security configurations are verified and working correctly.

### Mockups / Wireframes:
NA

### Product Name:
Beckn

### Domain:
NA

### Tech Skills Needed:
DevOps

### Complexity:
Medium

### Category:
Setup

### Sub Category:
Infrastructure

**Comment by prasad-takale-eminds** [comment]
We have created the k8s cluster and deployed the BPP PS on that k8s cluster. 
After the deployment, we shared the details with BE and QA team.
