### ISSUE TITLE
Beckn GUI :  Error When Joining Existing Network as BAP

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#131]
### Description

When attempting to join an existing network as a BAP using the following URL: [Beckn Onix GUI](https://beckn-onix-gui.vercel.app/), an error is encountered. The error message is currently vague, making it difficult to understand the root cause of the issue.

### Steps to Reproduce
1. Go to [Beckn Onix GUI](https://beckn-onix-gui.vercel.app/).
2. Click on **Installation Wizard**
3. Click on **Join an existing network**
4. Click on BAP Adapter
5. Enter Valid Subscriber ID, subscriber URL, Registry URL
6. Click on continue
7. Observe the error message that appears.

### Expected Behavior
- [ ] A clear and descriptive error message should be provided to help users understand what went wrong and how they can potentially resolve the issue.
- [ ] Include Mandatory Field requirement & validations wherever possible

### Actual Behavior
An unspecified error message is displayed, making it unclear what the problem is.

### Suggested Improvement
- Define the exact error with a clear and descriptive message.
- Provide details about what caused the error.

**Comment by Mishalabdullah** [comment]
@emmayank the URL https://beckn-onix-gui.vercel.app/ is mainly for showing the UI to other's.
When you are clicking the button for installing BAP adapter. What actually happening is the script trying to install set up the bap adapter on the vercel server.

now, vercel will not allow you to run custom scripts on their servers. it is free service for hosting websites only.

**Comment by Mishalabdullah** [comment]
@emmayank beckn-onix-gui.vercel.app is deployed on vercel,  we can only run serverless functions.
hence,  I am closing this issue.
