### ISSUE TITLE
Network Configuration URL for protocol server during installation

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#132]
Problem:
Currently during installation of protocol server we ask for a network configuration URL. Nothing happens to this input. 

Solution
The user should give the address of the Layer 2 Config at this place. Once it is provided, it should be copied into the schemas folder within the container for both the client and network parts of the Protocol Server being installed.

**Comment by viraj89** [comment]
To establish clarity and work with Venkatesh.

**Comment by vbabuEM** [comment]
Duplicate of #18

**Comment by vbabuEM** [comment]
Actually #18 
is the parent of 
#132
#133
#134

**Comment by viraj89** [comment]
This is a duplicate ticket for #18, hence marking this as closed.

**Comment by vbabuEM** [comment]
@viraj89 , the understanding was that 18 is a parent ticket and it has three child tickets - protocol-server, registry and gateway. You have left the other two as active and for discussion. Wouldnt it make sense to also have this as active and track the protocol server implementation independently?
Actually for protocol server we have a potential solution already available (i.e. copy the given file to the schemas folder within the container).
