### ISSUE TITLE
Network configuration URL for registry during installation

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#133]
Problem:
Currently during installation of registry we ask for a network configuration URL. Nothing happens to this input.

Solution
1. We should start a discussion on what network configuration means in the context of Registry
2. Based on the discussion, we should implement the same.

**Comment by viraj89** [comment]
To establish clarity and work with Venkatesh.

**Comment by vbabuEM** [comment]
Actually #18 
is the parent of 
#132
#133
#134

**Comment by viraj89** [comment]
This is already part of #18. 

And this needs collaborative discussion with the larger audience to make certain conclusions out of it. Moving it to next iteration for planning on discussion. cc @vbabuEM @faizmagic @yesrag2309 @emmayank

**Comment by prasad-takale-eminds** [comment]
I don't see the option where we are asking for the "network configuration URL" during registry installation. 

SS for registry installation. 
![Image](https://github.com/user-attachments/assets/6a065d8d-1ffd-4ddd-bd55-2cda79b85402)

Hence closing this ticket.
