### ISSUE TITLE
Network configuration URL for gateway during installation

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#134]
Problem:
Currently during installation of gateway we ask for a network configuration URL. Nothing happens to this input.

Solution

We should start a discussion on what network configuration means in the context of gateway
Based on the discussion, we should implement the same.

**Comment by vbabuEM** [comment]
Actually #18 
is the parent of 
#132
#133
#134

**Comment by viraj89** [comment]
This is already part of #18. 

And this needs collaborative discussion with the larger audience to make certain conclusions out of it. Moving it to next iteration for planning on discussion. cc @vbabuEM @faizmagic @yesrag2309 @emmayank

**Comment by prasad-takale-eminds** [comment]
I don't see the option where we are asking for the "network configuration URL" during gateway installation.

SS for gateway installation.
![Image](https://github.com/user-attachments/assets/6cb2761a-fb2b-4a59-a5bf-bac21fd2dcfe)


So, I'm closing this ticket.
