### ISSUE TITLE
Perform Horizontal Scaling After MongoDB Optimization

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#137]
## Description
We need to optimize MongoDB performance and then implement horizontal scaling for improved scalability and reliability.

## Goals
1. Optimize MongoDB configuration and query performance.
2. Set up a separate MongoDB instance with high configuration for horizontal scaling.
3. Create a MongoDB replica set for redundancy and failover.

## Expected Outcome
A horizontally scalable MongoDB setup that can handle increased load and ensure data availability.

## Acceptance Criteria
1. MongoDB optimization:
   - Analyze query performance and index usage.
   - Optimize queries and indexes.
   - Monitor resource utilization (CPU, memory, disk I/O).
2. Isolate MongoDB:
   - Set up a dedicated MongoDB instance with appropriate hardware resources.
   - Ensure proper security and access controls.
3. Create MongoDB replica set:
   - Configure multiple MongoDB nodes as a replica set.
   - Test failover scenarios.
   - Verify data consistency across nodes.

## Mockups / Wireframes
N/A (This section can be updated later if needed.)

## Product Name
Beckn

## Domain
Vistaar

## Tech Skills Needed
- Proficiency in MongoDB administration and optimization.
- Understanding of replica sets and sharding.

## Complexity
High

## Category
Database Management

## Sub Category
Horizontal Scaling

**Comment by shreyvishal** [comment]
Current Status: Have Isolated the MongoDB and created replica sets of MongoDB and tried testing the horizontal scaling but the result was similar to the test result without MongoDB optimization.

[Horizontal Scaling](https://docs.google.com/spreadsheets/d/1GOnIF8bRD-LvrVvhSuqleqxg-W3NLszeAwGMRGLSM3I/edit?gid=0#gid=0)
