### ISSUE TITLE
Check Beckn-Onix Mac Installation

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#144]
## Description
We need to verify the installation process of Beckn-Onix on Mac systems. This involves ensuring that the installation steps are clear, the software installs correctly, and all functionalities are working as expected on MacOS.

## Goals
- Verify the installation process of Beckn-Onix on Mac.
- Ensure all functionalities of Beckn-Onix are working correctly post-installation.
- Identify and document any issues encountered during the installation process.

## Expected Outcome
A verified and documented installation process for Beckn-Onix on Mac, with all functionalities working as expected and any issues identified and resolved.

## Acceptance Criteria
- [ ] Follow the installation steps for Beckn-Onix on Mac.
- [ ] Verify that the software installs correctly without errors.
- [ ] Test all functionalities of Beckn-Onix to ensure they work as expected.
- [ ] Document any issues encountered during the installation process.
- [ ] Provide recommendations for any improvements needed in the installation process.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
Onix

## Tech Skills Needed
- MacOS usage and troubleshooting
- Software installation and configuration
- Documentation skills

## Complexity
Medium

## Category
Installation Verification

## Sub Category
Software Installation

**Comment by shreyvishal** [comment]
Current Status: Done with the beckn-onix installation and testing on my MAC system and found that Gateway, Registry and Protocol Server Instance were running fine there was one issue with the docker config regarding passing OS architecture fixed that think and was working fine
