### ISSUE TITLE
Vertical scale Load testing of Gateway in Vistaar Instance

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#145]
## Description
We need to perform vertical scale load testing on the gateway deployed in the Vistaar instance to ensure it can handle increased load and traffic efficiently. This involves testing the gateway's performance under varying load conditions and identifying any potential bottlenecks.

## Goals
- Simulate high traffic scenarios to test the gateway's performance.
- Identify and document any performance bottlenecks.
- Ensure the gateway can scale vertically to handle increased load.
- Provide recommendations for performance improvements.

## Expected Outcome
A comprehensive report detailing the gateway's performance under load, including identified bottlenecks and recommendations for optimization.

## Acceptance Criteria
- [ ] Load testing scripts and configurations.
- [ ] Execution of load tests under different traffic conditions.
- [ ] Detailed performance report with metrics and analysis.
- [ ] Recommendations for performance improvements.
- [ ] Documentation of the load testing process and results.

## Mockups / Wireframes
N/A 

## Product Name
Beckn

## Domain
Vistaar

## Tech Skills Needed
- Vertical scale load testing
- Performance testing tools (e.g., JMeter, Locust)
- Kubernetes
- Networking concepts

## Complexity
High

## Category
Performance Testing

## Sub Category
Load Testing

**Comment by shreyvishal** [comment]
Current Status: Created Script for Gateway Load Testing on K6 and recorded the below metrics
[Metrics](https://docs.google.com/spreadsheets/d/1GOnIF8bRD-LvrVvhSuqleqxg-W3NLszeAwGMRGLSM3I/edit?gid=0#gid=0)
