### ISSUE TITLE
Vertical scale Load testing of Registry in Vistaar instance

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#146]
## Description
We need to perform vertical scale load testing on the registry deployed in the Vistaar instance to ensure it can handle increased load and traffic efficiently. This involves testing the registry's performance under varying load conditions and identifying any potential bottlenecks.

## Goals
- Simulate high traffic scenarios to test the registry's performance.
- Identify and document any performance bottlenecks.
- Ensure the registry can scale vertically to handle increased load.
- Provide recommendations for performance improvements.

## Expected Outcome
A comprehensive report detailing the registry's performance under load, including identified bottlenecks and recommendations for optimization.

## Acceptance Criteria
- [ ] Load testing scripts and configurations.
- [ ] Execution of load tests under different traffic conditions.
- [ ] Detailed performance report with metrics and analysis.
- [ ] Recommendations for performance improvements.
- [ ] Documentation of the load testing process and results.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
Vistaar

## Tech Skills Needed
- Vertical scale load testing
- Performance testing tools (e.g., JMeter, Locust)
- Kubernetes
- Networking concepts

## Complexity
High

## Category
Performance Testing

## Sub Category
Load Testing

**Comment by shreyvishal** [comment]
Current Status: Created Script for Registry Load Testing on K6 and recorded the below metrics
[Metrics](https://docs.google.com/spreadsheets/d/1STuT0cSAW373aC8IVD7craY20OAVM97gJjHtWShxanc/edit?gid=0#gid=0)
