### ISSUE TITLE
Debugging performances Testing Issue with Shreya and Omkar

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#154]
## Description
We are encountering performance issues during our testing phase. Shreya and Omkar will collaborate to debug and resolve these issues. The focus will be on identifying bottlenecks, optimizing performance, and ensuring the Jenkins node is functioning correctly.

## Goals
- Identify the root cause of the performance issues.
- Collaborate with Shreya and Omkar to implement a fix.
- Optimize the performance of the Jenkins node.
- Ensure smooth execution of performance tests.

## Expected Outcome
A stable and optimized Jenkins node with resolved performance issues, ensuring reliable performance testing.

## Acceptance Criteria
- [ ] Reproduce the performance issue in a controlled environment.
- [ ] Identify the root cause of the performance issue.
- [ ] Implement a fix for the identified issue.
- [ ] Verify the fix resolves the issue without introducing new problems.
- [ ] Document the debugging process, findings, and resolution steps.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
DevOps

## Tech Skills Needed
- Jenkins node management
- Performance testing
- Debugging and troubleshooting
- Collaboration and communication

## Complexity
High

## Category
Bug Fix

## Sub Category
Performance Testing

**Comment by prasad-takale-eminds** [comment]
Connected Shreya and Omkar to debug the K8s deployment which we have created for the performance testing.
