### ISSUE TITLE
Setup machine for BPP-PS-PF-Staging

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#155]
Hello Prasad,
                Can you please provide one machine with the following details:
 
bpp-ps-client-pf-staging.becknprotocol.io
bpp-ps-network-pf-staging.becknprotocol.io
 
It will have BPP PS. But if you do the domain name, SSL and Nginx for BPP-PS, I can install using Beckn-ONIX and connect to the Pupilfirst Staging server. This setup will be used by the Xplor team as the staging server for the skilling app.
 
Thanks with regards,
Venkatesh

**Comment by prasad-takale-eminds** [comment]
We have created EC2 instances and deployed the BPP PS PF staging, 
EC2 instances are as below. 

Instance ID | Name | Public IP | Private IP
-- | -- | -- | --
i-0f63e818924c9a74f | bpp-ps-pf-staging | 13.233.92.52 | 172.31.47.143
