### ISSUE TITLE
Create new server for MonogDB, Redis and RabbitMQ for performance testing

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#156]
## Description
We need to set up a new server to host MongoDB, Redis, and RabbitMQ for performance testing purposes. This server will be used to evaluate the performance of these services under various load conditions and ensure they can handle the expected traffic.

## Goals
- Set up a new server for MongoDB, Redis, and RabbitMQ.
- Configure each service for optimal performance.
- Conduct performance tests to evaluate the server's capabilities.
- Identify and document any performance bottlenecks.

## Expected Outcome
A fully functional server hosting MongoDB, Redis, and RabbitMQ, with performance testing completed and documented.

## Acceptance Criteria
- [ ] New server is set up and configured.
- [ ] MongoDB, Redis, and RabbitMQ are installed and configured.
- [ ] Performance tests are conducted and results are documented.
- [ ] Any performance bottlenecks are identified and documented.
- [ ] Recommendations for performance improvements are provided.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
Performance Testing

## Tech Skills Needed
- Jenkins Node
- MongoDB configuration and management
- Redis configuration and management
- RabbitMQ configuration and management
- Performance testing tools (e.g., JMeter, Locust)

## Complexity
High

## Category
Infrastructure

## Sub Category
Server Setup

**Comment by prasad-takale-eminds** [comment]
As requested by the BE team we have created separate EC2 instances for each supporting app of PS and made the required changes in the k8s deployment file.
