### ISSUE TITLE
Created New Docker Image for Protocol Server and Deployed it in Dev Environment

### ISSUE THREAD

**Issue by PritiEM** [beckn/beckn-onix#161]
## Description
We have created a new Docker image for the protocol server and successfully deployed it in the Dev environment. 

## Goals
- Build a new Docker image for the protocol server.
- Ensure the image includes the latest configurations and dependencies.
- Deploy the new Docker image in the Dev environment.

## Expected Outcome
A new, fully functional Docker image for the protocol server, deployed in the Dev environment, with all functionalities working as expected.

## Acceptance Criteria
- [ ] Build a new Docker image for the protocol server.
- [ ] Ensure the Docker image includes the latest configurations and dependencies.
- [ ] Deploy the Docker image in the Dev environment.

## Mockups / Wireframes
N/A (This section can be added if there are specific UI requirements.)

## Product Name
Beckn

## Domain
Protocol Server

## Tech Skills Needed
- Docker
- Kubernetes (for deployment)
- CI/CD pipeline management
- Troubleshooting and debugging

## Complexity
Medium

## Category
Infrastructure

## Sub Category
Containerization

**Comment by prasad-takale-eminds** [comment]
We have created the new docker image for the PS with the latest code changes and deployed it in dev env.
