### ISSUE TITLE
Beckn ONIX Benchmarking for vertical scalability

### ISSUE THREAD

**Issue by faizmagic** [beckn/beckn-onix#163]
## Description
The purpose of this exercise is to identify benchmarking and establish baseline numbers that are useful for Beckn or in general any mission project. If a mission project is expected to be used by X number of users, we will be able to determine the necessary resources, such as CPUs and RAM, required for vertical scaling.

- To be published in Starter Kit, Beckn Onix readme file, protocol server repos.
- Should be documented in Confluence page [here](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/496893978/Results+of+Vertical).

- The detailed flow document to be outlined [here](https://docs.google.com/document/d/1Yag41F0xn3qclGEZpNUzsYaW5w1RLkEcNjc03STcMBc/edit).

## Goals
- [ ] Set up a robust infrastructure with EC2 instances.
- [ ] Perform vertical scaling tests.
- [ ] Conduct comprehensive load testing using tools like K6.
- [ ] Isolate and test data storage components like MongoDB and Redis.
- [ ] Optimize resource allocation based on performance data.
- [ ] Document the scalability testing approach and results.
- [ ] Provide recommendations for network improvements.

## Expected Outcome
- A detailed report on the network's ability to handle increasing workloads and traffic while maintaining optimal performance.
- Documentation of the scalability testing approach and results.
- Recommendations for ensuring a reliable and scalable ecosystem.

## Acceptance Criteria
- [ ] Basic error rate test is completed.
- [ ] End-to-end message flow test (select request with on_select response) from BAP to BPP with at least 1 instances of BAP and 1 instances of BPP.
- [ ] Error rate of no missing response is less than 0.1% for 10000 requests (<10 failures) at at least 50 messages per second.
- [ ] Benchmarking details for Registry, Gateway, and Protocol Server are available on Confluence.
- [ ] Benchmarks of vertical scaling are noted.
- [ ] Documented results are shared on the Confluence page.

## Mockups / Wireframes
NA

## Product Name
Beckn Protocol ONIX

## Domain
Beckn Protocol

## Tech Skills Needed
DevOps, Kubernetes, Load Testing, EC2 Instances, MongoDB, Redis, K6

## Complexity
High

## Category
Testing

## Sub Category
Scalability and Performance Testing

**Comment by vbabuEM** [comment]
Ravi mentioned that we should publish the results as is and no work is scheduled for this sprint. I am assigning this back to Mayank. The task is now to publish the results we have. Faiz mentioned that we should be publishing the Vertical scaling results. Horizontal scaling needs more review. 

cc @ravi-prakash-v , @faizmagic , @viraj89 , @emmayank , @shreyvishal

**Comment by viraj89** [comment]
A separate flow for horizontal scalability is [here](https://github.com/beckn/beckn-onix/issues/181). 

Hence this ticket is ready to review and closure.

**Comment by viraj89** [comment]
While this activity was completed, the results were documented on Confluence page [here](https://fide-official.atlassian.net/wiki/spaces/BBB/pages/496893978/Results+of+Vertical). Thus, this ticket is ready for closure.
