### ISSUE TITLE
Create a DIY section on the website - Discovery

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#17]
In the newly build onix.developers.becknprotocol.io, we need a DIY area, where someone can try out the installation instructions above and see the network in operation without having to themselves get Cloud machines. There are things to consider including cost, security, feasibility etc. This deliverable does not have to be April 5 if tough to achieve. But it will be nice to have. We can have separate discussions on this

**Comment by vbabuEM** [comment]
Have noted down the issues in implementing this in this document https://fide-official.atlassian.net/wiki/x/CgAeEg and submitted to Ravi on April 3. There has not been any decision on the next steps. Will keep this issue open for some time or till that decision is made

**Comment by viraj89** [comment]
Feedback awaited from @ravi-prakash-v on this topic based on the last comment from @vbabuEM . 
Moving this to next iteration. 
cc @vbabuEM @faizmagic @yesrag2309 @emmayank

**Comment by prasad-takale-eminds** [comment]
We are still waiting for feedback from @ravi-prakash-v on this topic based on the comment from @vbabuEM.

CC: @emmayank @viraj89

**Comment by prasad-takale-eminds** [comment]
As of now we don't have clarity on this, and there is no specific interest in this so we are de-prioritising this. 
So we are closing this ticket and if required we will open new ticket for this.
