### ISSUE TITLE
Add missing core functionality details in the Beckn-Onix-Stack documentation

### ISSUE THREAD

**Issue by rajaneeshk90** [beckn/beckn-onix#174]
## Description

As per the last review of the Beckn-ONIX stack documentation, Ravi divided the functionalities into 2 groups, Core and Extened.

There were some core functionalities added in the functional requirements section, as part of this flow we need to 

- Go through the current docs
- Find the missing details
- Add them in the doc
- Review the doc again

## Goals
- [x] Go through the current docs
- [x] Find the missing details
- [x] Go through the existing KB about current Beckn-ONIX to understand the gap between the current Beckn-ONIX doc and the current Beckn-ONIX implementation.
- [x] Add them in the doc
- [x] Review the doc again

## Expected Outcome
By the end of this task, the Beckn-Onix-Stack docs should have the core functionalities added.

## Acceptance Criteria
- [x] The identified core functionalities are added in Beckn-ONIX specification doc.

## Mockups / Wireframes
N/A

## Product Name
Beckn

## Domain
Beckn-Onix

## Tech Skills Needed
- Familiarity with the Beckn-Onix stack
- Experience with full-stack development

## Complexity
High

## Category
Development

## Sub Category
Stack Enhancement

**Comment by faizmagic** [comment]
@rajaneeshk90 , please update if see blockers

CC: @ravi-prakash-v , @emmayank

**Comment by rajaneeshk90** [comment]
Tech standup: discussion and update regarding the task. Discussion regarding representing it as a milestone. setting up a milestone.
