### ISSUE TITLE
Beckn-ONIX installed PS has layer 2 check only in client

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#178]
### Description:
By default, the Beckn-ONIX installed Protocol Server (PS) has the Layer 2 check enabled only in the BAP-Client and BPP-Client. It is not enabled in the BAP-Network and BPP-Network. This inconsistency can lead to potential security and performance issues in the network.

### Goals:
- [ ] Ensure that the Layer 2 check is enabled in all four instances: BAP-Client, BAP-Network, BPP-Client, and BPP-Network.

### Expected Outcome:
- Consistent Layer 2 check across all four instances (BAP-Client, BAP-Network, BPP-Client, and BPP-Network) in the Beckn-ONIX installed PS.
- Improved security and performance due to the uniform application of Layer 2 checks.

### Acceptance Criteria:
- [ ] Layer 2 check is successfully enabled in BAP-Client, BAP-Network, BPP-Client, and BPP-Network.
- [ ] Testing confirms that Layer 2 checks are functioning correctly in all instances.

### Mockups / Wireframes:
NA

### Product Name:
Beckn-ONIX Protocol Server

### Domain:
DevOps

### Tech Skills Needed:
Beckn-ONIX, Protocol Server Configuration, Network Security

### Complexity:
Medium

### Category:
Configuration

### Sub Category:
Security and Performance

**Comment by prasad-takale-eminds** [comment]
Code changes are done for layer 2 configuration. 
PR https://github.com/beckn/beckn-onix/pull/142

**Comment by viraj89** [comment]
@prasad-takale-eminds - please add comments/screenshots as necessary. cc @emmayank

**Comment by prasad-takale-eminds** [comment]
@viraj89 @emmayank , 

We don't need to attach screenshots for this as the PR number is already mentioned in the previous comment.

**Comment by emmayank** [comment]
**Review Completed**

**Proof of Completion**
<img width="951" alt="image" src="https://github.com/user-attachments/assets/9017a402-409c-4495-b60e-837208296f61">
