### ISSUE TITLE
Create High-Quality Template Webhook for Network Participants

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#182]
## Description
Network Participants have requested a high-quality webhook template, as the current webhook on Sandbox is of low quality despite maintaining code standards. We need to provide a reference webhook sample in Node.js to assist Network Participants.

## Goals
- [x] Develop a high-quality webhook template in Node.js.
- [x] Ensure the webhook template adheres to best coding practices.
- [x] Provide clear documentation for the webhook template.
- [x] Make the webhook template available for Network Participants as a reference.

## Expected Outcome
- A high-quality, well-documented webhook template in Node.js.
- The webhook template should be easy for Network Participants to use and integrate.
- Documentation should clearly explain the usage and customization of the webhook.

## Acceptance Criteria
- [x] The webhook template is developed in Node.js and adheres to best coding practices.
- [x] Documentation is provided, including usage instructions and examples.
- [ ] The template is tested and verified for quality and functionality.
- [x] The webhook template is made available on the appropriate platform for Network Participants.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Tech Debt

## Tech Skills Needed
Node.js, Webhook Development, Documentation

## Complexity
Medium

## Category
Development

## Sub Category
Webhook Template

**Comment by vbabuEM** [comment]
1. Write a Application Server using good design patterns (NestJS?)
2. It should expose one endpoint (webhook)
3. Any call to that endpoint should return back an ACK to the caller (BPP-Client)
4. Based on the action, it should create a worker thread for that action
5. In the thread we mention that business logic goes here in comment
6. At end of worker thread call the corresponding on_xxxx (on_search, on_select) etc with a fixed json for a particular domain (retail)
7. Create a postman collection for retail that one can use on a BAP.
8. It should be possible to deploy this webhook as a retail simulator on any Beckn network and see communication flow in and out.
9. Make sure to log the request and the response, so it can be used for debugging. If possible have a health and logs endpoint for this webhook where health returns 200 and logs shows the request/response log (optional)
10. Create documentation on installing and hooking up webhook to a beckn network. 

cc. @rahul-eminds @emmayank @viraj89 @faizmagic @meenakshi2468

**Comment by yesrag2309** [comment]
@rahul-eminds - Please update the working status by EOD and get it verified with @vbabuEM. Post that please close the ticket.

@faizmagic

**Comment by yesrag2309** [comment]
@rahul-eminds - Can you please share the status on this ticket.

@viraj89 / @emmayank - Kindly check with @rahul-eminds on the status.

@faizmagic

**Comment by emmayank** [comment]
Review Completed
1. PR is raised, approved by @vbabuEM  and merged

**Comment by yesrag2309** [comment]
@emmayank - Can we please close this card if all tasks are completed

@viraj89 @faizmagic
