### ISSUE TITLE
[ChargeZone] - Beckn Onix - fix the issues

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#183]
## Description
We need to identify and resolve various issues within the Beckn Onix platform. This includes bug fixes, performance improvements, and enhancements to ensure the platform operates smoothly and efficiently. 

## Goals
- [ ] Identify and document all existing issues within Beckn Onix.
- [ ] Prioritize issues based on their impact and urgency.
- [ ] Implement fixes for high-priority issues.

## Expected Outcome
A stable and reliable Beckn Onix platform with all identified issues resolved. Users should experience improved performance and fewer disruptions, leading to a better overall experience.

## Acceptance Criteria
- [ ] All identified issues are documented and prioritized.
- [ ] The platform shows improved performance and stability.
- [ ] The platform operates smoothly without major disruptions.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Onix

## Tech Skills Needed
- Bug Tracking and Resolution
- Performance Optimization
- Quality Assurance and Testing

## Complexity
High

## Category
Maintenance

## Sub Category
Bug Fixes and Performance Improvements

**Comment by ankitShogun** [comment]
Connected with the charge zone team through various means. They are currently checking the docs and will let us know if they face any issue. No action is needed from our side at the moment.
@faizmagic @viraj89

**Comment by ankitShogun** [comment]
Someone from the chargezone team approached me regarding setting up things using beckn onix for their specific scenario. Got on a call and helped the fellow. Closing this ticket

**Comment by emmayank** [comment]
**Review completed.**

No PR Required. only on-call fix and on-call support
