### ISSUE TITLE
Deep Dive into Beckn Onix Protocol Server Component

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#185]
## Description
This task involves a comprehensive analysis of the protocol server component of the Beckn Onix. The focus will be on understanding key functionalities such as signature validation, schema validation, and the correct processing of acknowledgments (ACK) and negative acknowledgments (NACK). Specific areas of investigation include:

1. Understanding how signature validation is implemented and ensuring it functions correctly.
2. Gaining insight into schema validation mechanisms and verifying their accuracy.
3. Verifying that ACK and NACK responses are received properly in various scenarios.
4. Ensuring that NACK responses include all appropriate details, aiding in debugging and troubleshooting.

Do share the report updates as comment on this same issue ticket. 

## Goals
- [x] Understand the implementation of signature validation in the protocol server.
- [x] Analyze and comprehend the schema validation process.
- [ ] Verify the correct reception of ACK and NACK responses.
- [ ] Ensure that NACK responses contain detailed and relevant information.

## Expected Outcome
- A clear understanding of the protocol server's signature and schema validation processes.
- Confirmation that ACK and NACK responses are functioning correctly.
- Identification of any potential issues with NACK response details, with recommendations for improvements if necessary.

## Acceptance Criteria
- [x] Documentation of the signature validation process and its current state.
- [x] Detailed analysis of the schema validation process with findings.
- [ ] Successful testing to ensure ACK and NACK responses are being correctly handled.
- [ ] Report on the completeness and accuracy of NACK details, with suggestions for any required enhancements.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Beckn ONIX

## Tech Skills Needed
Beckn Protocol, Signature Validation, Schema Validation, API Testing, Debugging

## Complexity
Medium

## Category
Development

## Sub Category
Analysis

**Comment by ankitShogun** [comment]
Spent time on protocol server repo for understanding the code. Synced up with shreya whenever needed. Also understood how this single code-base server the need for 4 different entities (BAP-Client, BAP-Network, BPP-Client, BPP-Network)

Signature/Header validation is done between BAP and BPP but the internal entities trust each other (BAP client and BAP Network users the same header). Adding some summary about how json schema validation and header validation are done using middleware in the protocol server code-base


## 1. `authValidatorMiddleware`
- **File**: `src/middlewares/auth.middleware.ts`
- **Purpose**: This middleware is responsible for validating the authentication of incoming requests. It ensures that the request has the necessary authentication tokens and that they are valid.
- **How it works**: 
  - When a request is received, this middleware checks for the presence of authentication tokens (like JWT or API keys) in the request headers.
  - It then verifies these tokens to ensure they are valid and have not expired.
  - If the tokens are valid, the request is allowed to proceed to the next middleware or route handler.
  - If not, an error response is sent back to the client indicating that authentication has failed.
- **Detailed Explanation**:
  - **Step 1**: The middleware logs the transaction ID and the source of the request (BAP Network or BG).
  - **Step 2**: It retrieves the `authorization` and `proxy-authorization` headers from the request.
  - **Step 3**: It checks if authentication is required based on the application configuration.
  - **Step 4**: If authentication is required, it verifies the `authorization` and `proxy-authorization` headers using the `verifyHeader` function from `auth.utils.ts`.
    - **Verification Process**:
      - The `verifyHeader` function splits the `authorization` header into its components.
      - It retrieves the subscriber details (including the public key) using the `getSubscriberDetails` function.
      - It creates a signing string using the `createSigningString` function.
      - It verifies the signature using the `verifyMessage` function.
        - **verifyMessage Function**:
          - **Load Sodium Library**: Ensures the Sodium library is ready.
          - **Convert Inputs**: Converts the signed message and public key from Base64 to binary format.
          - **Verify Signature**: Uses `crypto_sign_verify_detached` to verify the signature.
          - **Return Result**: Returns `true` if the signature is valid, `false` otherwise.
  - **Step 5**: If both headers are verified, it retrieves the sender details using the `getSenderDetails` function and stores them in `res.locals`.
  - **Step 6**: If verification fails, it sends a 401 Unauthorized response.
- **Example**:
  ```typescript
  import { authValidatorMiddleware } from "../middlewares/auth.middleware";
  responsesRouter.post(`/${action}`, authValidatorMiddleware, ...);
  ```

## 2. `authBuilderMiddleware`
- **File**: `src/middlewares/auth.middleware.ts`
- **Purpose**: This middleware is used to build the authentication tokens for outgoing requests. It adds the necessary authentication headers to the request.
- **How it works**: 
  - Before sending a request to another service, this middleware generates the required authentication tokens and adds them to the request headers.
  - This ensures that the outgoing request is authenticated and can be processed by the receiving service.
- **Detailed Explanation**:
  - **Step 1**: The middleware logs that it is building the authentication header.
  - **Step 2**: It creates the authentication header configuration using the request body.
  - **Step 3**: It sets the `authorization` header in the request.
  - **Step 4**: It retrieves the sender details and stores them in `res.locals`.
  - **Step 5**: It calls the `next` function to pass control to the next middleware or route handler.
- **Example**:
  ```typescript
  import { authBuilderMiddleware } from "../middlewares/auth.middleware";
  requestsRouter.post(`/${action}`, authBuilderMiddleware, ...);
  ```

**Comment by ankitShogun** [comment]
For ACK and NACK below were the only places in the code where I could find them being used. Still verifying some scenarios like how do we get the NACK in case of layer 2 config missing


## 1. `bapNetworkResponseHandler`
- **File**: `src/controllers/bap.response.controller.ts`
- **Purpose**: This function handles responses from the BAP network. It sends an ACK response if the request is valid and within the TTL (Time-To-Live) period. If the request is delayed or invalid, it sends a NACK response.
- **Instances**:
  - **ACK**: Sent when a valid response is received within the TTL period.
  - **NACK**: Sent when a delayed message is received or if the request cache is not found.
- **Example**:
  ```typescript
  if (requestCache) {
    const now = moment().valueOf();
    const { timestamp = 0, ttl = 0 } = requestCache as any;
    if (((now - timestamp) / 1000) > ttl) {
      // Delayed message
      logger.info(
        `\Delayed message received at BAP Network message id: ${message_id}\n\n`
      );
      acknowledgeNACK(res, req.body.context, {
        code: 6781616,
        message: `Response timed out for ${message_id} and action:${requestAction}, as requestCache not found`,
        type: BecknErrorType.coreError,
      });
      return;
    }
  }
  acknowledgeACK(res, req.body.context);
  ```

## 2. `bapClientTriggerHandler`
- **File**: `src/controllers/bap.trigger.controller.ts`
- **Purpose**: This function handles client triggers for the BAP. It sends an ACK response if the request is valid and the client type is webhook. If the request is missing required fields, it sends a NACK response.
- **Instances**:
  - **ACK**: Sent when a valid request is received and the client type is webhook.
  - **NACK**: Sent when the request is missing required fields like `bpp_id` or `bpp_uri`.
- **Example**:
  ```typescript
  if (
    action != RequestActions.search &&
    (!bpp_id || !bpp_uri || bpp_id == "" || bpp_uri == "")
  ) {
    acknowledgeNACK(res, req.body.context, {
      code: 6781616,
      message: `All triggers other than search requires bpp_id and bpp_uri. \nMissing bpp_id or bpp_uri at ${protocolServerLevel}`,
      type: BecknErrorType.contextError
    });
    return;
  }
  if (getConfig().client.type == ClientConfigType.webhook) {
    acknowledgeACK(res, req.body.context);
  }
  ```

**Comment by emmayank** [comment]
**Review Completed**

The ticket contains proof of completion , as the high level summary understanding of the components of protocol server
