### ISSUE TITLE
Beckn-Onix end to end testing and verification of environment setups

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#186]
## Description
This task involves a detailed testing and verification process for setting up the environment, executing scripts, handling edge cases, performing end-to-end testing scenarios, and conducting post-installation verification for various services in a Docker-based environment. The focus will be on ensuring that all necessary components and services are correctly installed, configured, and operational. The steps include:

1. **Preparation**
   - Setting up the environment with Docker and Docker Compose.
   - Configuring environment variables and ensuring scripts are correctly sourced.

2. **Script Execution**
   - Testing individual functions like `install_package`, `start_container`, and `update_registry_details`.
   - Verifying service installations for the registry, gateway, support services, and protocol servers.

3. **End-to-End Testing Scenarios**
   - Executing a full setup on a local machine and verifying the functionality of all components.
   - Testing network creation and joining scenarios.

4. **Post-Installation Verification**
   - Checking logs and outputs for errors or warnings.
   - Conducting connectivity tests between services.

5. **Cleanup**
   - Cleaning up Docker containers, volumes, and networks after testing to prevent conflicts.

## Goals
- [ ] Ensure the environment is correctly set up with all necessary configurations.
- [ ] Verify the functionality of key script functions and service installations.
- [ ] Handle edge cases gracefully with appropriate error handling.
- [ ] Successfully execute end-to-end testing scenarios.
- [ ] Conduct thorough post-installation verification.
- [ ] Clean up the environment after testing.

## Expected Outcome
- A fully functional environment with all services correctly installed and configured.
- Identification and resolution of any issues or errors during script execution.
- Documentation of the testing process, including any edge cases encountered.

## Acceptance Criteria
- [ ] Successful setup of the environment with all necessary configurations.
- [x] All key functions and services tested and verified for proper operation.
- [ ] Edge cases handled with meaningful error messages.
- [ ] End-to-end testing scenarios completed without issues.
- [ ] Post-installation verification showing all services running as expected.
- [ ] Environment cleaned up with no residual conflicts.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
DevOps

## Tech Skills Needed
Docker, Docker Compose, Shell Scripting, Service Configuration, Networking

## Complexity
High

## Category
Testing

## Sub Category
Automation

**Comment by ankitShogun** [comment]
1. Tried to setup individual components locally but was facing an issue. Will get a remote machine running with the help of prasad and then will setup all the individual components.
2. Also plan to do the nginx configuration myself.
3. Found the individual functions of beckn-onix.sh script file. Will test them individually

**Comment by ankitShogun** [comment]
1. Installed each product individually on a single ec2 instance
2. Used nginx as a proxy server for re-routing to each product
3. Verified each product individually
4. Explored a lot about how nginx work and how to operate it
5. Adding SSL certificates for all the product URLs and adding sub domain names for each product


Screenshot of registry working 

![Image](https://github.com/user-attachments/assets/37c0f047-3a68-4374-ab2e-854ab829a021)

**Comment by ankitShogun** [comment]
Facing some issues with the gateway. Checking somethings again @faizmagic @viraj89

**Comment by ankitShogun** [comment]
Had to add a network domain on the registry side and then restart the registry and gateway. Unclear about the necessity. It is also not mentioned in the beckn onix doc



![Image](https://github.com/user-attachments/assets/8b82d7a8-bc95-41cf-a571-b6b0bb2008ae)

**Comment by emmayank** [comment]
Review Completed

 Feedback  - @ankitShogun  @rahul-eminds 
1. test for negative scenarios during installation
2. test for complete feature visible in the cli

share it again for the review

**Comment by ankitShogun** [comment]
Issue 1
1. Start installation
2. Click on 2, create a new production network
3. The wizard shows Registry, Gateway, BAP and BPP. But it should only show registry.

Issue 2
1. Start installation
2. Click on 4, Merge multiple networks
3. It shows Two options. Click on 1. Merge two different registries
4. Enter two registry options
5. It fails saying invalid option

Issue 3
1. Start installation
2. Click on 4, Merge multiple networks
3. It shows Two options. Click on 2. Merge Multiple Registries into a super registry
4. Enter wrong addresses
5. It will succeed

Issue 4
1. Start installation
2. Click on 5, Configure existing network
3. Clicking on any of Gateway/BAP/BPP will do the same as installation of Gateway/BAP/BPP. So what is the difference

Issue 5
During BAP installation if we do not give /subscribers suffix to registry, it accepts the input but the installation fails as its unable to contact the registry. This should be stopped through input validation itself

Issue 6
1. Start installation
2. Click on 6 (non existing item)
3. It still goes ahead

Issue 7
Url format is not checked during installation - everywhere

Issue 8
1. Start installation
2. Click on 1, join existing network
3. Press a (non-existing option)
4. It will go ahead with installation

Issue 9
Listed in the comments above

**Comment by emmayank** [comment]
Review Completed
