### ISSUE TITLE
Understanding of Beckn Onix

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#191]
## Description
This issue aims to facilitate a comprehensive understanding of the Beckn Onix framework. 

## Goals
- [x] Detailed study of the Beckn Onix framework.
- [x] Document the key functionalities and components.

## Expected Outcome
A well-documented and thoroughly understood Beckn Onix framework, with team members equipped with the necessary knowledge to effectively utilize and implement it in projects.

## Acceptance Criteria
- [x] Key functionalities and components clearly outlined.
- [x] Knowledge base created and accessible to all team members.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Onix

## Tech Skills Needed
- In-depth knowledge of Beckn Onix framework
- Documentation and technical writing skills

## Complexity
Medium

## Category
Knowledge Sharing

## Sub Category
Training and Documentation

**Comment by rahul-eminds** [comment]
Went through documentations, diagrams, etc to under beckn onix and its working.

**Comment by emmayank** [comment]
**Review Completed**

He is able to install BecknOnix in his system, and have the understanding of the beckn onix

![Image](https://github.com/user-attachments/assets/be798b75-3517-4eae-b1e3-e044a9d79287)
