### ISSUE TITLE
End to End testing of Beckn Onix

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#192]
## Description
This issue focuses on conducting comprehensive end-to-end testing of the Beckn Onix framework. The goal is to ensure that all components and functionalities work seamlessly together, identifying and resolving any issues that may arise during integration.

## Goals
- [x] Develop a detailed test plan covering all aspects of Beckn Onix.
- [x] Execute end-to-end tests to validate the integration of all components.

## Expected Outcome
A thoroughly tested Beckn Onix framework with all components functioning correctly and any identified issues resolved, ensuring a reliable and robust system ready for deployment.

## Acceptance Criteria
- [x] All end-to-end tests executed as per the test plan.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Onix

## Tech Skills Needed
- Proficiency in Beckn Onix framework
- Experience with end-to-end testing methodologies

## Complexity
High

## Category
Testing

## Sub Category
End-to-End Testing

**Comment by rahul-eminds** [comment]
While testing found the issues:
Create an ubuntu EC2 instance and tried set up in local machine and found the few issues:
1) while installing for the first time without docker installed, throws daemon socket permission error. However, after logout and then login into the machine this works fine.
2) Generated Public and Private key shows in logs for BAP, but it does not display for BPP. Just show display message generating public/private key.
3) Public and Private keys generated for gateway are not showing in swf.properties of gateway.
4) Public and Private keys generated for registry are not showing in swf.properties of registry.
5) By default there are no layer 2 config schemas in bap client, so throwing 422 error.
6) When reinstalled beckn onix after deleting docker instances, BAP and BPP 's default.yml are not updated but it is updated in registry

**Comment by emmayank** [comment]
**Review Completed**

1. while installing for the first time without docker installed, throws daemon socket permission error. However, after logout and then login into the machine this works fine. - **Acknowledged, reported as issue**
2. Generated Public and Private key shows in logs for BAP, but it does not display for BPP. Just show display message generating public/private key. -  - **Acknowledged, reported as issue**
3. Public and Private keys generated for gateway are not showing in swf.properties of gateway.  - **invalid issue it should not be visible**
4. Public and Private keys generated for registry are not showing in swf.properties of registry. - **invalid issue it should not be visible**
5. By default there are no layer 2 config schemas in bap client, so throwing 422 error. - **Acknoweledged, reported as issue**
6. When reinstalled beckn onix after deleting docker instances, BAP and BPP 's default.yml are not updated but it is updated in registry - **Invalid issues**
 

@rahul-eminds  please create similar ticket in current iteration and continue on the testing. need to do in-depth testing
