### ISSUE TITLE
Update Debian Docker Repo in Beckn-Onix Installation

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#193]
## Description
Currently, during the installation, Beckn-Onix uses the Ubuntu repository for Docker with the apt package manager. This repository is not supported on Debian OS. For Debian OS, we need to use the official Debian repository for Docker.

## Goals
- [ ] Identify the current usage of the Ubuntu Docker repository in the installation scripts.
- [x] Update the installation scripts to use the official Debian Docker repository for Debian OS.
- [ ] Test the updated installation process on Debian OS to ensure compatibility.
- [x] Ensure that the installation process remains functional on Ubuntu OS.

## Expected Outcome
- The installation scripts should correctly use the official Debian Docker repository when installing on Debian OS.
- The installation process should be seamless and error-free on both Debian and Ubuntu OS.

## Acceptance Criteria
- [ ] The installation scripts are updated to use the official Debian Docker repository for Debian OS.
- [x] The installation process is tested and verified to work on Debian OS.
- [ ] The installation process continues to work on Ubuntu OS without any issues.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
Onix

## Tech Skills Needed
- Shell scripting
- Familiarity with Docker installation processes
- Knowledge of Debian and Ubuntu package management
- Testing and debugging skills

## Complexity
Medium

## Category
Installation

## Sub Category
Package Management

**Comment by prasad-takale-eminds** [comment]
Updated the installation script to install latest docker version for Debian. 
PR: https://github.com/beckn/beckn-onix/pull/190

This fix will resolve issue [#97](https://github.com/beckn/beckn-onix/issues/97) as well.
