### ISSUE TITLE
Enhance beckn-onix to support system upgrade without losing previous data

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#2]
## Description

Improve the existing Onix-Beckn installation script to ensure it retains previous installations and configurations during updates. The script should provide users with the option to either update the existing system or perform a fresh installation, based on their preference.

#### Approach:
1. **Script Assessment**:
   - Evaluate the current Onix-Beckn installation script to understand its functionalities and limitations.
   - Identify areas where the script removes older installations and configurations.

2. **Enhancement Strategy**:
   - Modify the script to detect existing installations and configurations.
   - Implement logic to prompt users for their preference - update or fresh installation.
   - Ensure that the script retains older configurations if the user chooses to update the system.
   - If the fresh installation is selected, the **previous configurations will be archived(rename with _date) not deleted.**

#### Key Considerations:
- **User Experience**:
  - Prioritize user experience by providing clear prompts and options during script execution.
- **Configuration Retention**:
  - Ensure that the script does not overwrite or remove existing configurations during updates.
- **Version Management**:
  - Implement robust version detection and upgrade mechanisms to facilitate seamless updates.

**Script must be tested at least 5 time with success than only should be merged.**

## Goals

- [ ] Script must retain the older configurations if available.

## Expected Outcome

- The Onix-Beckn installation script will be updated to provide users with the option to update or perform a fresh installation.
- The script will intelligently detect existing installations and configurations and retain them during updates.
- Update will not remove/effect the the existing installation unless the user requests for a fresh installation.

## Acceptance Criteria

- [ ] Script must run properly without getting into issue.
- [ ] The script must execute as mentioned above.

**Comment by mayurvir** [comment]
@vbabuEM can you confirm if this issue is closed and the related PR for it?

**Comment by vbabuEM** [comment]
@mayurvir  As I mentioned in the previous comment, the three PRs listed there ensure the data is not lost. However the script itself does not have the upgrade of components flow. We can either write a separate ticket for that or edit this to specify that we need a path in the script to upgrade individual components (registry/gateway/BAP PS/BPP PS)
