### ISSUE TITLE
Add Validation for Registry URL Suffix During Beckn ONIX Setup

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#205]
## Description
When setting up Beckn ONIX, particularly under Option 2 and then selecting either Option 2 (BAP) or Option 3 (BPP), add a validation check to ensure that the provided registry URL ends with the suffix /subscriber. This validation is necessary because the installation process will fail without this specific URL structure.

## Goals
- [x] Ensure that the registry URL provided by users during setup includes the required /subscriber suffix.
- [x] Prevent installation errors by enforcing this validation.

## Expected Outcome
1. If a user provides a registry URL that does not end with /subscriber, an error message should be displayed, and the user should be prompted to correct the URL before proceeding.
2. The installation should only continue if the registry URL is correctly formatted.

## Acceptance Criteria
- [x] When setting up Beckn ONIX with Option 2 and selecting either BAP (Option 2) or BPP (Option 3), the system validates the registry URL to ensure it ends with /subscriber.
- [x]  If the registry URL is invalid (does not end with /subscriber), an error message is displayed, and the user is prompted to enter a correct URL.
- [x]  The installation process proceeds only when a valid registry URL is provided.
- [x]  The code changes are reviewed and approved by the development team.
- [x]  The updated setup process is tested to ensure the validation works correctly without causing other issues.

## Mockups / Wireframes
N/A

## Product Name
Beckn ONIX 

## Domain
N/A

## Tech Skills Needed
Devops

## Complexity
High

## Category
Deployment

## Sub Category
Installation

**Comment by prasad-takale-eminds** [comment]
We have fixed the code and added the suffix validation for the registry URL. 
PR: https://github.com/beckn/beckn-onix/pull/216

![Image](https://github.com/user-attachments/assets/a308f2ed-c287-4f15-8502-e77f6618ec54)

**Comment by emmayank** [comment]
Review Completed
