### ISSUE TITLE
Add Docker Command Permission Validation During Beckn ONIX Installation

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#208]
## Description
Implement validation to check Docker command permissions for the user during the Beckn ONIX installation process. When installing for the first time without Docker installed, the process currently throws a daemon socket permission error. This error should be properly handled, ensuring that the installation process checks for Docker installation and appropriate user permissions before proceeding.

## Goals
- [x] Validate that Docker is installed and the user has the necessary permissions to run Docker commands.
- [x] Prevent installation from proceeding if Docker is not installed or the user lacks the necessary permissions, and provide clear guidance on how to resolve the issue.

## Expected Outcome
1. During installation, a check is performed to ensure Docker is installed and the user has the required permissions to execute Docker commands.
2. If Docker is not installed or there are permission issues, an error message is displayed, and the installation process is halted until the issue is resolved.
3. Clear instructions are provided to the user on how to install Docker or resolve permission issues.

## Acceptance Criteria
- [x]  A validation check is added during the Beckn ONIX installation process to ensure Docker is installed and the user has appropriate permissions.
- [x]  If Docker is not installed, the user is informed with an error message, and the installation process is stopped.
- [x]  If the user lacks Docker command permissions, an error message is displayed, and the installation is halted.
- [x]  The user is provided with clear instructions on how to install Docker or adjust permissions to resolve the issue.
- [x]  The code changes are reviewed and approved by the development team.
- [x]  The installation process is tested to ensure the validation works correctly and handles errors gracefully.

## Mockups / Wireframes
N/A

## Product Name
Beckn ONIX 

## Domain
N/A

## Tech Skills Needed
Devops

## Complexity
High

## Category
Deployment

## Sub Category
Installation

**Comment by prasad-takale-eminds** [comment]
The necessary code fix has been pushed to the repository. Since we pushed the code to the same branch, it automatically merged into the existing pull request (PR).
PR: https://github.com/beckn/beckn-onix/pull/216

Please check below SS 
![Image](https://github.com/user-attachments/assets/e727347c-469e-446d-8c72-7bbdc9000fae)

**Comment by emmayank** [comment]
Review Completed
