### ISSUE TITLE
UEI specification: review an existing PR, remove issues, add changes suggested by RAVI

### ISSUE THREAD

**Issue by rajaneeshk90** [beckn/beckn-onix#218]
## Description
This task involves reviewing an existing Pull Request (PR) for the UEI specification. The goal is to remove any issues identified and incorporate the changes suggested by Ravi. This will ensure the specification is up-to-date and meets the required standards.

## Goals
- [ ] Review the existing PR for the UEI specification.
- [ ] Identify and remove any issues present in the PR.
- [ ] Implement the changes suggested by Ravi.
- [ ] Ensure the updated specification aligns with the overall objectives of UEI.

## Expected Outcome
A thoroughly reviewed and updated UEI specification document that incorporates all necessary changes and resolves any existing issues, ensuring it is ready for implementation.

## Acceptance Criteria
- [ ] The PR has been reviewed and all issues have been addressed.
- [ ] All changes suggested by Ravi have been implemented.
- [ ] The document is clear, concise, and free of ambiguities.
- [ ] The document aligns with the overall objectives of UEI.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
UEI

## Tech Skills Needed
- Technical writing
- Code review
- Familiarity with UEI standards
- Understanding of Beckn protocol

## Complexity
Medium

## Category
Documentation

## Sub Category
Specification Review

**Comment by rajaneeshk90** [comment]
**actions taken as part of this task:**

- Venkatesh pointed out the mistakes in the example jsons of the main branch of the UEI github repository.
- Went through the examples jsons in the main branch of the UEI specification github repository.
- filtered out the errors.
- fetched the pending PRs raised in the past which solves the issues, discussed with Ravi to merge those PRs, Ravi suggested some changes in the PR.
- Had a sync with Mayank to get the context on the PR that he had raised, to clarify the doubts Ravi had.
- Went through an old email, read the document mentioned in the mail to get the context on the PR.
- Made changes after getting the context.

**Changes made so far:**

- Changing the issues in the example jsons.
- validating each json using the beckn-spec-validator tool to make sure that they dont have any errors.
- convert the example jsons into example yaml to include them into the specification yaml.

**Link to the commits so far**: 

- https://github.com/beckn/Unified-Energy-Interface/pull/18/commits/ce7cc2b11058355f0135e3e0ba0c90517b06ac0a
- https://github.com/beckn/Unified-Energy-Interface/pull/18/commits/a946a818042ab64ede75b2363415aab52a8409a1

**Comment by rajaneeshk90** [comment]
This is not fully completed yet. The PRs has been created. 

still exploring the options to add one click experience of the UEI examples. ex, add a button/link on the git page so that users can try out the APIs.

Closing this ticket as partially completed (for hour management of the iteration). Will reduce the hours of this ticket.

Will create a new ticket for button option exploration.

**Comment by yesrag2309** [comment]
Based on the above @rajaneeshk90 comment closing this flow and @rajaneeshk90 please create the new ticket and add it in the current iteration please [If you have already done it please ignore & share the card number]

@viraj89 @emmayank @faizmagic

**Comment by rajaneeshk90** [comment]
Here is the ticket tracking the button option: https://github.com/beckn/beckn-onix/issues/229
