### ISSUE TITLE
Add Layer 2 config prompt back to installation

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#222]
**Problem**
When Beckn-ONIX was first demonstrated, it had the following prompt:

"Paste the URL of the network configuration here (or press Enter to skip)"

At that time, this was not linked to anything and so on a review comment, we had removed this prompt. 

Subsequently, now we mandatorily need layer 2 config for BAP and BPP. The behaviour of layer 2 for Registry and Gateway is still not defined. So we can re-add this prompt to the installation of BAP and BPP. 

**Solution**
1. During the installation of the BAP and BPP after asking the user for registry, subscriber_id, subscriber_url and webhook_url(for BPP), prompt the user to enter the layer 2 configuration.
"Paste the URL of the Layer 2 configuration here (or press Enter to skip)"
2. If the user gave a web url, store it in a variable.
3. Continue with the installation including the successful message (Installation success must be separate from download success). 
4. Now if the user had given a value, then call the "../layer2/download_layer_2_config_bap.sh" with the path (The shell file might have to be modified to take command line params) for the BAP. Use the download_layer_2_config_bpp.sh for BPP.
5. If the user has not given a value, show the message 
    BAP - "Use the download_layer_2_config_bap.sh file in the ../layer2 folder to download your required layer 2 config files"
    BPP - "Use the download_layer_2_config_bpp.sh file in the ../layer2 folder to download your required layer 2 config files"

**Comment by vbabuEM** [comment]
Related to #210

**Comment by prasad-takale-eminds** [comment]
I’ve made the necessary changes to the script for the Layer2 configuration during the BAP installation. Below are the screenshots showing the test cases:

1. **Screenshot with correct Layer2 Configuration URL:**

   ![Correct Layer2 Configuration URL](https://github.com/user-attachments/assets/42ce7d6d-8884-4658-aabe-207d2ba66b71)

2. **Screenshot showing the error when the Layer2 Configuration URL is incorrect or the download fails:**

   ![Incorrect Layer2 Configuration URL](https://github.com/user-attachments/assets/fe033803-d820-4b5f-94cb-49e165ed99b5)

3. **Screenshot if the user skips entering the Layer2 Configuration URL:**

   ![User Skips Layer2 Configuration URL](https://github.com/user-attachments/assets/b410703a-35e6-4906-b756-59a209d26d15)


I will replicate the same for the BPP installation.

**Comment by vbabuEM** [comment]
This sounds fine Prasad. Please go ahead. @prasad-takale-eminds

**Comment by prasad-takale-eminds** [comment]
I’ve made the necessary changes to the script for the Layer2 configuration during the BPP installation. Below are the screenshots showing the test cases:

1. **Screenshot with correct Layer2 Configuration URL:**

  ![Correct Layer2 Configuration URL](https://github.com/user-attachments/assets/4b0d074a-db62-4579-a299-da703cf67514)


2. **Screenshot showing the error when the Layer2 Configuration URL is incorrect or the download fails:**

  ![Incorrect Layer2 Configuration URL](https://github.com/user-attachments/assets/e09aa922-1cde-4d68-bf38-109355239503)


3. **Screenshot if the user skips entering the Layer2 Configuration URL:**

 ![User Skips Layer2 Configuration URL](https://github.com/user-attachments/assets/3ad7491b-3e28-43ea-87e1-ae29c84ae7b1)

**Comment by prasad-takale-eminds** [comment]
PR for layer 2 config installation. 
https://github.com/beckn/beckn-onix/pull/227

**Comment by emmayank** [comment]
Review Completed
