### ISSUE TITLE
Send logs to stdout of Docker for Registry and Gateway

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#224]
## Description
Configure Docker containers for the Registry and Gateway services to send logs to stdout. This ensures better log visibility and allows easier monitoring and troubleshooting using Docker logging mechanisms.

## Goals
- [x] Configure Registry service to send logs to stdout in Docker.
- [x] Configure Gateway service to send logs to stdout in Docker.
- [x] Ensure logs are easily accessible for monitoring and troubleshooting.

## Expected Outcome
- The Registry and Gateway services send logs to stdout in Docker containers, improving log visibility.
- Logs are accessible through Docker’s logging mechanisms, enabling easier troubleshooting and monitoring.

## Acceptance Criteria
- [x] Logs from the Registry service are successfully routed to stdout.
- [x] Logs from the Gateway service are successfully routed to stdout.
- [x] Logs are verified as accessible via Docker logging mechanisms and are functioning correctly.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
- Docker
- Logging Configuration
- Registry and Gateway Services
- Monitoring Tools

## Complexity
Medium

## Category
DevOps

## Sub Category
Logging and Monitoring

**Comment by prasad-takale-eminds** [comment]
We have updated the docker image for the gateway and registry to send the application logs stdout. 

SS Gateway 
![Image](https://github.com/user-attachments/assets/30d5791c-97ff-4329-a6d1-d7074cb0d803)

SS Registry 
![Image](https://github.com/user-attachments/assets/54207a85-ec2c-4b6e-a548-9a1ef941f41f)

SS Docker image of the gateway
![Image](https://github.com/user-attachments/assets/43aeb286-64e6-4192-80ba-e69c3066e265)


SS Docker image of the registry
![Image](https://github.com/user-attachments/assets/c84707e5-0fed-452c-af1b-91b99e2f585a)

**Comment by emmayank** [comment]
Review Completed
