### ISSUE TITLE
Review and Rework: Beckn-ONIX specification: Creating a new specification doc only with the core functionalities

### ISSUE THREAD

**Issue by yesrag2309** [beckn/beckn-onix#226]
## Back Story
@rajaneeshk90 has sent this for review to Ravi and Binu & Tanya from ONDC (Binu has added some comments and those have been resolved). The review request has been sent on Sep 6.
The deliverable for this is part of the document here: https://docs.google.com/document/d/1JlE-JTgQCPVPtFUqs3dIfBma3Koi_pVsO4LwB4hGcM8/edit#heading=h.m1mzlygez2v3

Review and Rework is tracking under the current iteration (Sep16-Sep29th)

## Reference Ticket
https://github.com/beckn/missions/issues/99

**Comment by rajaneeshk90** [comment]
Not much of discussion happened regarding this in this Iteration. Closing the ticket.

One thing that is pending is that we need to publish [this](https://docs.google.com/document/d/1JlE-JTgQCPVPtFUqs3dIfBma3Koi_pVsO4LwB4hGcM8/edit#heading=h.m1mzlygez2v3) document. Need to confirm with Ravi about where we are going to publish this.
