### ISSUE TITLE
Infra Optimization - AWS usage

### ISSUE THREAD

**Issue by Kathirvel-ai** [beckn/beckn-onix#275]
- [ ] Document the AWS infra landscape in confluence
- [ ] Review and see if further optimization is possible
- [ ] Document the findings and take necessary actions

**Comment by Kathirvel-ai** [comment]
Scheduled a call with Faiz Oct 29 (2:30 PM) to review the landscape.

**Comment by faizmagic** [comment]
Mayank to plan a review call today

**Comment by emmayank** [comment]
**Current Status :**
1. Review call conducted, action item are listed here - https://github.com/beckn/beckn-utilities/issues/228

**Next Step**
1. Conduct review call on 7th Nov, 2024 to review shutdown instance for permanent deletion
2. Conduct review call next week to review further action items.

**Comment by emmayank** [comment]
**Current Status :** 
1. Permanently deleted 194 Stopped isntance
2. Progress on some items from this ticket -https://github.com/beckn/beckn-utilities/issues/228


**Next Step:** 
1. Completed all task from this ticket - https://github.com/beckn/beckn-utilities/issues/228

**Comment by faizmagic** [comment]
@emmayank , Please update the details of the cost optimisation as part of the monthly forecast

**Comment by emmayank** [comment]
**Current Status :**
1. As result of Infra cost optimization, aws monthly forecast amount is reduced to 40% as compared to last month. (i.e, $3112)
![Image](https://github.com/user-attachments/assets/d1cac17d-3b8b-4dd6-9817-78bdaa7988c0)


**Next Step:**
1. Further Optimization plan discussion

**Comment by yesrag2309** [comment]
@emmayank - Based on discussion with @faizmagic last week please mention what needs to be done in the current week.
@viraj89
