### ISSUE TITLE
On-Call Support with Decharge Network Team to Fix Beckn-Onix GUI Related Issue

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#288]
## Description
Provide on-call support to the Decharge network team to resolve GUI-related issues in the Beckn-Onix application. This involves collaborating with the Decharge team to identify, troubleshoot, and fix any user interface problems affecting the usability or functionality of the Beckn-Onix application.

## Goals
- [x] Connect with the Decharge network team to understand the GUI issue in detail.
- [x] Troubleshoot and identify the root cause of the issue affecting the Beckn-Onix GUI.
- [x] Implement and/or recommend fixes to resolve the identified GUI issue.
- [x] Conduct testing to confirm that the fix resolves the issue and does not introduce additional problems.

## Expected Outcome
A resolved GUI-related issue in the Beckn-Onix application, with confirmation from the Decharge network team that the application is functioning as expected.

## Acceptance Criteria
- [x] On-call support session is conducted with the Decharge network team to address the GUI issue.
- [x] Fixes are implemented and verified to resolve the issue effectively.
- [x] Testing confirms that the Beckn-Onix GUI is fully operational post-fix, with no additional issues.

## Mockups / Wireframes
NA

## Product Name
Beckn-Onix

## Domain
TBD

## Tech Skills Needed
- GUI Troubleshooting
- Real-Time Support
- Issue Identification and Resolution
- Communication with Network Team

## Complexity
Medium

## Category
Support

## Sub Category
On-Call Support

**Comment by prasad-takale-eminds** [comment]
PS client and network were not picking the correct default.yml file. The team used the GUI to deploy the application after deleting the client's docker container, and the network application was deployed successfully.
