### ISSUE TITLE
beckn-onix github correction

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#3]
## Description

onix should be renamed to beckn-onix , all the places in GitHub including

1. Repo name
2. Readme files
3. Installation guides
4. Scripts
5. Scripts prompt and comments

and any other place where we have mentioned onix it should be renamed to beckn-onix.

**The develop and main branches are not in sync and certain files are not being used, please remove those files.**

## Goals

- [ ] onix must be replaced in all the places to beckn-onix.
- [ ] Github branches should be corrected and must have relevant files only.

## Expected Outcome

All the places onix must be replaced with beckn-onix.
Github is cleaned up and branches are in sync.

## Acceptance Criteria

- [ ] onix replaced with beckn-onix
- [ ] All branches cleaned and in sync.

**Comment by vbabuEM** [comment]
The rename of ONIX to Beckn-ONIX is done. Please use this task to fix other issues such as older installation file
