### ISSUE TITLE
Specification for Beckn One v0.5

### ISSUE THREAD

**Issue by yesrag2309** [beckn/beckn-onix#300]
## Description

Beckn One related specification works will be tracking under this main flow ticket.

**Focus areas under Beckn One:**
1. UPPCL-P1
2. IGM
3. RSP
4. Network Observability-P2
5. Open Network Volunteering-P1

## Associated Tickets

Beckn-One: Trust Layer(Persistence Layer) API specification v0.1 - [Click Here](https://github.com/beckn/beckn-onix/issues/298)
Beckn One: Network observability Specification version 0.1: Review and Feedback - [Click Here](https://github.com/beckn/beckn-onix/issues/294)
Beckn One: IGM Specification version 0.1: Review and Feedback - [Click Here](https://github.com/beckn/beckn-onix/issues/291)
Beckn-ONIX specification: version 0.2: Review, Feedback, Rework - [Click Here](https://github.com/beckn/beckn-onix/issues/290)

**Comment by rajaneeshk90** [comment]
This ticket will be closed as the iteration is over. future work will be done as part of a new ticket.

will link the ticket here once it is created.
