### ISSUE TITLE
Create Release Note and Prepare for Release of Beckn-Onix v0.5

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#328]
## Description
Create the release notes and prepare for the official release of version 0.5 of Beckn-Onix. This release includes a series of bug fixes and improvements to enhance the installation and functionality of the Beckn-Onix system.

## Goals
- [x] Document the release notes highlighting the fixes and features of Beckn-Onix v0.5.
- [x] Prepare all necessary materials and steps for the v0.5 release.
- [x] Validate the changes and ensure readiness for deployment.

## Included Fixes and Features
1. **Add Validation for Registry URL Suffix During Beckn ONIX Setup** (#205)
2. **Add URL Validator Throughout Beckn ONIX Installation** (#206)
3. **Add Input Number Validation During Beckn ONIX Installation** (#207)
4. **Docker Command Permission Validation During Beckn ONIX Installation** (#208)
5. **Update Key Generation Logging for BAP Setup in Beckn ONIX** (#209)
6. **Add Layer 2 Config Prompt Back to Installation** (#222)
7. **Role Permissions Not Present in Beckn-ONIX Installed Registry** (#93)
8. **Beckn-ONIX Installation Does Not Update Existing Key** (#177)
9. **Beckn-ONIX Is Registering Using Wildcard Domain** (#188)
10. **Added Message to Not Available in the Current Distribution** (#204)
11. **Provide an Option During Install to Update Components** (#189)
12. **Add Option to Install All Beckn Components** (#271)

## Expected Outcome
A finalized release note for v0.5 and successful preparation for its release, ensuring all listed fixes and features are included and tested.

## Acceptance Criteria
- [x] A comprehensive release note is created for v0.5.
- [x] All fixes and features are verified as included in the release.
- [x] Preparation steps for the release are completed.
- [ ] Release note is approved and shared with stakeholders.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
Documentation, Release Management, Validation Testing

## Complexity
Medium

## Category
Release Preparation

## Sub Category
Release Notes

**Comment by prasad-takale-eminds** [comment]
Here are the links for the draft release note, PR, and testing report:  
- **Release Note:** [[Beckn Onix Releases](https://github.com/beckn/beckn-onix/releases)](https://github.com/beckn/beckn-onix/releases)  
- **Pull Request:** [[PR #308](https://github.com/beckn/beckn-onix/pull/308)](https://github.com/beckn/beckn-onix/pull/308)  
- **Testing Report:** [[Report #329](https://github.com/beckn/beckn-onix/issues/329)](https://github.com/beckn/beckn-onix/issues/329)
