### ISSUE TITLE
End-to-End QA of Beckn Onix from beckn-onix-v0.5 Branch

### ISSUE THREAD

**Issue by emmayank** [beckn/beckn-onix#329]
## Description
Perform comprehensive end-to-end QA testing for the Beckn Onix system using the `beckn-onix-v0.5` branch. The testing will ensure that all functionalities, workflows, and integrations introduced in version 0.5 are fully validated and meet the quality standards.

## Goals
- [x] Conduct end-to-end functional testing for all workflows.
- [x] Validate fixes and features included in the v0.5 branch.
- [x] Ensure system stability and identify any regressions or issues.
- [x] Document all test scenarios, findings, and resolutions.

## Expected Outcome
A validated Beckn Onix system from the `beckn-onix-v0.5` branch with all functionalities and fixes thoroughly tested and approved for release.

## Acceptance Criteria
- [x] All key workflows and functionalities are tested and validated.
- [x] Fixes and features introduced in v0.5 are verified.
- [x] No critical or high-severity issues remain.
- [x] A detailed QA report is prepared and shared with stakeholders.

## Mockups / Wireframes
NA

## Product Name
Beckn

## Domain
TBD

## Tech Skills Needed
QA Testing, Functional Testing, Regression Testing, Documentation

## Complexity
Medium to High

## Category
Testing

## Sub Category
End-to-End QA

**Comment by prasad-takale-eminds** [comment]
We performed end-to-end testing of Beckn Onix using the `beckn-onix-v0.5` branch and encountered an issue with user login. This required updating the RolePermission on the registry and configuring the NP with the provided user. After resolving the issue, we re-tested the script, and it is now functioning as expected.

Below are the screenshots documenting each stage of the testing process, along with the associated issue numbers:

**Validation for Registry URL Suffix #205**  
![Image](https://github.com/user-attachments/assets/ed19db9d-0cdf-4bae-975f-e5dfdfff94e3)

**URL validation #206**  
![Image](https://github.com/user-attachments/assets/937e1004-8b34-40a1-a5b2-e4d787c9fef8)

**Input number validation #207**  
![Image](https://github.com/user-attachments/assets/a2e7e55e-1c0b-4bb0-af6e-473f426bd988)

**Docker Command Permission Validation #208**  
![Image](https://github.com/user-attachments/assets/632e10da-666a-4793-a706-3b4298f47ac7)

**Layer2 Configuration URL #222**  
![Image](https://github.com/user-attachments/assets/0c701f46-adca-49eb-b0eb-6746afc8def2)

**User skips entering the Layer2 Configuration URL**  
![Image](https://github.com/user-attachments/assets/c445150e-f5b3-4671-8f2c-620ac8358976)

**Registry RolePermission #93**  
![Image](https://github.com/user-attachments/assets/9c5bbc02-fe55-46c2-ba04-34061b212ec7)

**Registry UI with role permission**  
![Image](https://github.com/user-attachments/assets/f4b85242-d93e-45bc-b776-64f0012a7f3c)

**Option during installation to update components #189**  
![Image](https://github.com/user-attachments/assets/2cb02372-1e24-48eb-9688-cc4e19de670d)

**Username/password authentication for PS deployment #177**  
![Image](https://github.com/user-attachments/assets/65a6a96d-18fc-4f2e-927e-3eaf4a8c0002)

**Prompt user for domain input #188**  
![Image](https://github.com/user-attachments/assets/ff772ed8-0622-49c2-8e03-7a84e1ccd9a2)

**NP with provided domain on UI**  
![Image](https://github.com/user-attachments/assets/a83014d7-d4d5-42b5-a08e-9652fabbac75)

**Without domain**  
![Image](https://github.com/user-attachments/assets/291d59b8-e727-4acf-9289-a0bb8f7c1167)

**Domain not available on the registry; shows available domains**  
![Image](https://github.com/user-attachments/assets/63a03749-c3d9-46e6-b724-3421e422c385)

**Display message for unavailable features #204**  
![Image](https://github.com/user-attachments/assets/2d0259a0-aa14-4a0d-a69a-e20e08ae2907)

**Add support for installing all components #271**  
![Image](https://github.com/user-attachments/assets/26d71891-2a5b-4851-b692-db985db1faff)
