### ISSUE TITLE
Create volumes outside of the installation folder

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#4]
Problem:
Currently if we install Beckn-Onix the local installation folder is bind-mounted to the container. This kind of setup is primarily for development purposes. When you try to pull a new version of installation, the configuration files are overwritten. 

Requirement:
Instead of bind-mounts, change the installation to use volumes that are stored outside of the installation folder.

**Comment by vbabuEM** [comment]
@vishi24 , please associate a high priority for this issue. Thank you.

**Comment by prasad-takale-eminds** [comment]
We have fixed this issue for the registry and gateway.
