### ISSUE TITLE
Kubernetes deployment scripts for Protocol server

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#42]
**Name: protocol-server
Title: "Kubernetes Deployment script"**

**Description**

The protocol server has docker-based deployment scripts but there are no scripts that can be used to deploy the protocol server on Kubernetes. Need to write Kubernetes script which can be used in production environment for deployment.

The first step is to document the files and configuration needed for the K8S script - https://fide-official.atlassian.net/wiki/spaces/BBB/pages/262242307/ONIX+Kubernetes+scripts

**Goals:**
Document the files and configurations required for Kubernetes deployment.
Create Kubernetes script for protocol server deployment.

**Expected Outcome:**
Document the deployment files and the configurations in the deployment files.
Working scripts for deployment of the protocol server on Kubernetes.

**Acceptance Criteria:**
Document with list of deployment files and the configurations for the deployment.
Working scripts for deployment of the protocol server on Kubernetes.

**Project:**
Beckn

Organization Name:
Beckn Open Collective

Domain:
Others

**Tech Skills Needed:**
• Understanding of protocol server
• Nodejs
• Docker
• Kubernetes
• Basic understanding of rabbitMQ and Redis

**Comment by mayurvir** [comment]
Outdate.
