### ISSUE TITLE
Kubernetes deployment scripts for beckn-sandbox

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#43]
## Description
Current deployment scripts of the sandbox  support deployment of the sandbox on docker, but cannot be used to deploy the services on Kubernetes.

## Goals

- [ ] Creation of Kubernetes deployment script for sandbox .

## Expected Outcome

- Working deployment scripts for all the services and infra required for the sandbox  .
- The services that need autoscaling should have horizontal pod scalers.
- Services which needs to be exposed should have service deployment.
- It must have a config file that will contain all configuration properties.
- Ingres should be defined for accessing from outer world.

## Acceptance Criteria

- [ ] The script should be working properly on kubernetes.
- [ ] The script should be tested on AWS.
- [ ] The script should work with infra containers and managed services also.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

### Tech Skills Needed:

Docker
Kubernetes

### Complexity

High

### Category

Deployment

### Sub Category

Deployment

**Comment by mayurvir** [comment]
Out of date. Not required
