### ISSUE TITLE
Kubernetes deployment script for sandbox-webhook

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#44]
## Description
Current deployment scripts of the sandbox webhook support deployment of the sandbox webhook  on docker, but cannot be used to deploy the services on Kubernetes.

## Goals

- [ ] Creation of Kubernetes deployment script for sandbox webhook.

## Expected Outcome

- Working deployment scripts for all the services and infra required for the sandbox webhook .
- The services that need autoscaling should have horizontal pod scalers.
- Services which needs to be exposed should have service deployment.
- It must have a config file that will contain all configuration properties.
- Ingres should be defined for accessing from outer world.

## Acceptance Criteria

- [ ] The script should be working properly on kubernetes.
- [ ] The script should be tested on AWS.
- [ ] The script should work with infra containers and managed services also.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

### Tech Skills Needed:

Docker
Kubernetes

### Complexity

High

### Category

Deployment

### Sub Category

Deployment

**Comment by faizmagic** [comment]
We are looking at merging webhook to sandbox BPP, hence there is no fix required.  This ticket can be closed
