### ISSUE TITLE
ONIX - Kubernetes deployment scripts - Parent ticket

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#45]
## Description

ONIX script is not written to deplo the applications on the container cluster and other is no container orchestration in the current version. Now to improve the scalability of the ONIX components the script needs to be enhanced to use container orchestration for that purpose will be used as container orchestration tool.

Kubernetes deployment scripts need to be written for the below individual components and then used in the ONIX installer

1. Protocol server -BAP
2. Protocol server -BPP
3. Registry
4. Gateway

** The same deployment script of the protocol server can be used for BAP and BPP only change will be in values.yml.

Individual tickets will be created in their respective repositories. 

## Goals

- [ ] Kubernetes deployment scripts for protocol server.
- [ ]  Kubernetes deployment scripts for the registry.
- [ ]  Kubernetes deployment scripts for gateway.
- [ ]  Kubernetes deployment scripts for webhook.

## Expected Outcome

Kubernetes script for the above-mentioned services.

## Acceptance Criteria

- [ ] Working Kubernetes script for the above-mentioned services.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

NA

### Project Name

NA

### Organization Name:

[Organization Name]

### Domain

[Area of governance]

### Tech Skills Needed:

DevOps

### Complexity

High

### Category

DevOps

### Sub Category

Kubernetes
Scripting

**Comment by faizmagic** [comment]
This ticket can be closed, as there is no parent ticket required to manage the kubernetes tickets
