### ISSUE TITLE
ONIX - Load test  - script/plan

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#46]
## Description

There is no benchmarking done for the ONIX components in terms of hardware configuration and transactions that can be handled by applications running on specific infra. Load testing will include testing of the below components.

Protocol server - BAP
Protocol server - BPP
Registry and Gateway
Webhook
*Sandbox - this is not required for load test but considering this will be required to work as BPP we need to set this up.

Each of the components with their respective dependencies will be hosted on individual EC2 instances on Docker.
A different machine will be used for making load test requests.

**For this load testing, we will be using JMeter.**

## Goals

- Create the test plan/load scripts for performing this load testing.

## Expected Outcome

A working load test/ plan should include all the endpoints for discovery, fulfillment, and post-fulfillment.

## Acceptance Criteria

Working test plan that can be used to load test the ONIX components.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

ONIX

### Tech Skills Needed:

ONIX
Load testing

### Complexity

Medium

### Category

Testing

### Sub Category

Load testing

**Comment by mayurvir** [comment]
Ravi - Very low priority
To be taken up later if needed as a separate issue.
