### ISSUE TITLE
ONIX - load testing

### ISSUE THREAD

**Issue by vishi24** [beckn/beckn-onix#47]
## Description

There is no benchmarking done for the ONIX components in terms of hardware configuration and transactions that can be handled by applications running on specific infra. Load testing will include testing of the below components.

Protocol server - BAP
Protocol server - BPP
Registry and Gateway
Webhook
*Sandbox - this is not required for load test but considering this will be required to work as BPP we need to set this up.

Each of the components with their respective dependencies will be hosted on individual EC2 instances on Docker.
A different machine will be used for making load test requests.

This will be a load test session, to test the components.
1. Provisioning of EC2 instances.
2. Deployment of components using ONIX script.
3. Deployment of testing tool. (Can run from local system also)
4. Test plan execution.
5. Destroying the infra provisioned for load testing.
6. Documentation of the test results.(Documentation efforts will be an extra)

## Goals

- Load-test the components and document the test results.

## Expected Outcome

A proper document listing the intent , infra configuration and the outcomes of the load test.

## Acceptance Criteria

Document with below details

1. Test Name/ID: Unique identifier for the load test.
2. Test Configuration: Details about the test setup, including parameters such as number of virtual users, ramp-up time, test duration, etc.
3. Test Environment: Description of the hardware, software, and network environment used for the test.
4. Test Execution Time: Duration of the load test.
5. Metrics: Performance metrics collected during the test, such as response time, throughput, error rate, etc.
6. Summary: Summary of the test results, including average response time, peak load, etc.
7. Graphs/Charts: Visual representations of performance metrics over time, such as response time graph, throughput graph, etc.
8. Scenarios: Description of the test scenarios executed during the load test.

## Implementation Details

NA

## Mockups / Wireframes

NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name

ONIX

### Project Name

ONIX

### Tech Skills Needed:

ONIX
Load testing

### Complexity

Medium

### Category

Testing

### Sub Category

Load testing

**Comment by mayurvir** [comment]
Ravi - Very low priority.
To be closed and taken up later as a separate issue.
