### ISSUE TITLE
Discovery: Impact of making core specification strict

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#49]
The Beckn yaml core specification has a couple of behaviours that are relevant to this issue.
1. It uses the required attribute very sparsely
2. It does not prevent additional properties in objects.

These two behaviours together result in message implementations that are wrong. One example of this is the following:
1. Catalog object has Providers object. However in a specific implementation from the ODR domain, Providers object had come to the upper level. This passes the Protocol Server Yaml specification, though clearly it should have been flagged as error.

Before we go ahead and tighten the screws on strictness in the protocol, run a discovery task to identify what the impact of the tightening will have on existing implementations. Test the tightened version on the following and prepare a report.
1. Sample jsons from various domains present in sandbox/spec repositories
2. Logs from existing networks that we have access to. 

The objective of the report will be to provide the business with an idea on the impact of tightening the specs.

**Comment by mayurvir** [comment]
To be moved to core.
