### ISSUE TITLE
Rename Beckn-ONIX testbed machines to be inline with new addressing scheme

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#58]
Please add the subdomain mapping, Nginx configuration, and SSL for the following machines

registry-onix.becknprotocol.io
	ec2-13-234-122-88.ap-south-1.compute.amazonaws.com

gateway-onix.becknprotocol.io
	ec2-3-110-77-187.ap-south-1.compute.amazonaws.com

bap-ps-client-onix.becknprotocol.io
bap-ps-network-onix.becknprotocol.io
	ec2-65-0-185-230.ap-south-1.compute.amazonaws.com

bpp-ps-client-onix.becknprotocol.io
bpp-ps-network-onix.becknprotocol.io
bpp-unified-vendure-onix.becknprotocol.io (port 3000)
	ec2-13-233-35-236.ap-south-1.compute.amazonaws.com

Please also remove the following subdomain mappings
onix-registry.becknprotocol.io
onix-gateway.becknprotocol.io
onix-bap.becknprotocol.io
onix-bpp.becknprotocol.io

**Comment by prasad-takale-eminds** [comment]
We have re-configured the old Onix registry, gateway, BAP, and BPP.
We have configured DNS entry, SSL, Nginx configuration and Setup using Onix script for below. 

registry-onix.becknprotocol.io
ec2-13-234-122-88.ap-south-1.compute.amazonaws.com

gateway-onix.becknprotocol.io
ec2-3-110-77-187.ap-south-1.compute.amazonaws.com

bap-ps-client-onix.becknprotocol.io
bap-ps-network-onix.becknprotocol.io
ec2-65-0-185-230.ap-south-1.compute.amazonaws.com

 DNS entry, SSL, Nginx configuration done for below only Setup is pending  that @vbabuEM is going to take care. 

bpp-ps-client-onix.becknprotocol.io
bpp-ps-network-onix.becknprotocol.io
bpp-unified-vendure-onix.becknprotocol.io (port 3000)
ec2-13-233-35-236.ap-south-1.compute.amazonaws.com
