### ISSUE TITLE
Make selection of layer 2 config file more flexible

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#94]
Currently the Protocol Server installed as part of Beckn-ONIX chooses the layer 2 config file based on the following logic:
It concatenates the context.domain field with context.version field with underscore as separator and adds .yaml as suffix. Additionally if there is a colon in the resulting string, it replaces it with an underscore. 

This fixed scheme is a bit rigid. For example if there are multiple retail related domains created, and if all of them have same layer_2 config file, we have no choice right now than copy the file under all those different names.

Ravi was of the opinion that we should come up with some kind of logic to express the file to be used dynamically. He likened it to preprocessing. The exact logic can be arrived after brainstorming. It should cover as many different usecases such as the above.

**Comment by viraj89** [comment]
To establish clarity and work with Venkatesh.

**Comment by viraj89** [comment]
Already discussions on this topic are initiated on this ticket here - https://github.com/beckn/protocol-server/discussions/195

**Comment by vbabuEM** [comment]
@viraj89 , we should find some method wherein the issue itself is tracked in some manner. Maybe a flow or something. Because now that you have closed this issue, there will be no one who will drive the discussion to a change in software.
