### ISSUE TITLE
Search Provider - Create New Gateway Instance for BOC Environment

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#95]
### Description
Venky has created a Search provider to fulfill search requests from the cache. To integrate this, we need to fork Venky's repository and create a new Gateway instance on AWS using ONIX. The URL for the new Gateway will be `gateway-boc.becknprotocol.io`. Additionally, the existing registry of the BOC environment should be pointed to this new Gateway.

### Goals
- [ ] Fork Venky's repository for the Search provider.
- [ ] Create a new Gateway instance on AWS using ONIX.
- [ ] Assign the URL `gateway-boc.becknprotocol.io` to the new Gateway instance.
- [ ] Point the existing registry of the BOC environment to the new Gateway.

### Expected Outcome
A new Gateway instance on AWS with the URL `gateway-boc.becknprotocol.io` that integrates Venky's Search provider and is connected to the existing BOC environment registry.

### Acceptance Criteria
- [ ] Venky's repository for the Search provider is forked.
- [ ] A new Gateway instance is created on AWS using ONIX.
- [ ] The URL `gateway-boc.becknprotocol.io` is assigned to the new Gateway instance.
- [ ] The existing registry of the BOC environment is successfully pointed to the new Gateway.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn

### Domain
Infrastructure

### Tech Skills Needed
- AWS EC2
- ONIX
- DevOps

### Complexity
High

### Category
Infrastructure

### Sub Category
Gateway Configuration

**Comment by prasad-takale-eminds** [comment]
We have deployed the new BOC gateway for the search provider. 
Screenshots for the same. 
EC2 Instance. 

![image](https://github.com/beckn/beckn-onix/assets/84436945/fdd5b019-0b91-419f-b26b-30867ccbf14b)

Beckn-Onix script. 
![image](https://github.com/beckn/beckn-onix/assets/84436945/859cc2a1-2640-4ee6-88a0-e102defbcb5b)

Nginx

![image](https://github.com/beckn/beckn-onix/assets/84436945/746db904-d16d-4177-946c-75e84c6df77e)

DNS
![image](https://github.com/beckn/beckn-onix/assets/84436945/c3837aca-757c-4e5d-91f2-caada9115966)
