### ISSUE TITLE
Error installing on EC2 - Reported on BOC

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#97]
https://discord.com/channels/933320455903907840/1247447145137573949/1247447145137573949
Ddhruv
I was able to clone the ONIX in an ec2 instance, I have configured a SSL and used the domain provided by EC2, now once I give the domain for registry setup, some issue is coming up as 

................Installing Registry service................
unknown shorthand flag: 'f' in -f
See 'docker --help'.

Now, this was not expected, but it can be due to different versions of docker, etc. Then finally the Onix shows the registry installation is completed but the server is not started.
Error in some docker command
Installs but server is not  started

Ddhruv
OP
 — Yesterday at 12:59 PM
Found the problem, in the installation file, its given as "docker compose -f", where as it should look like "docker-compose -f"

**Comment by balessan** [comment]
Here is Benoit from Startin'blox (France). We are diving into Beckn for some projects.

We are in the phase of setting up the Onix Project on EC2 Test instances and we do have the same error, could a patch be released please ?

**Comment by Mishalabdullah** [comment]
@balessan 
I also faced the same issue. And this is how I resolved it.

### Step 1

Not sure why I noticed that when running docker-compose, it was showing segmentation fault.

### Step 2

I tried deleting all docker files using 

```
sudo apt  purge docker docker-compose docker-init
```
This did not work.

I was still able to execute docker commands.

### Step 3

I used the `whereis` command to find the where all the docker files are situated and deleted using the `rm command`
```
whereis docker
whereis docker-compose
```
Now deleting it 

```
sudo rm /usr/bin/docker
sudo rm /usr/bin/docker-compose
```
Like wise, deleted all the docker files manually.

At last for my Debian Machine went to the official docker docs and installed it from there .

![website link](https://docs.docker.com/engine/install/debian/)

**Comment by prasad-takale-eminds** [comment]
@balessan Please install the latest docker version on you system and then try. 
Make sure you have Docker version 27.1.2, build d01f264 and above. 
The docker-compose no longer being actively maintained. [Link](https://docs.docker.com/reference/compose-file/legacy-versions/)

@Mishalabdullah Please remove the docker from you Debian machine and reinstall the latest version of docker. 
For Debian please follow official steps [here](https://docs.docker.com/engine/install/debian/#install-using-the-repository)

**Comment by prasad-takale-eminds** [comment]
Docker package installation script is updated which will install the latest docker if docker is not installed previously. 
PR: https://github.com/beckn/beckn-onix/pull/190

**Comment by emmayank** [comment]
**Review Completed**

@prasad-takale-eminds  please merge the PR as @vbabuEM has already approved it
