### ISSUE TITLE
Layer 2 config changes in the Protocol Server are only done in client instances

### ISSUE THREAD

**Issue by vbabuEM** [beckn/beckn-onix#98]
**Problem**:
When we install BAP or BPP Beckn Adapter using Beckn ONIX, the Protocol Server config file is modified to set two configuration attributes. 
1. useLayer2Config
2. mandateLayer2Config
Both these attributes are set to true for Beckn-ONIX networks. However currently the installer sets these true only for the BAP-Client and BPP-Client. They are not set to true for BAP-Network and BPP-Network. Due to this the BAP Network and BPP Network do not perform Layer 2 validation checks and only do validation checks against the core.

**Solution**:
Beckn ONIX installation of BAP and BPP Beckn Adapter should enable Layer 2 Config validation on all the four PS components - BAP-Client, BAP-Network, BPP-Client, BPP-Network

**Comment by viraj89** [comment]
Duplicate for this - https://github.com/beckn/beckn-onix/issues/178
Hence marking this as closed.

**Comment by emmayank** [comment]
**Review Completed**

Code changes are done for layer 2 configuration.
PR https://github.com/beckn/beckn-onix/pull/142
