### ISSUE TITLE
Verify and document Ubuntu versions for Beckn ONIX

### ISSUE THREAD

**Issue by viraj89** [beckn/beckn-onix#99]
### Description
The goal of this ticket is to verify and document the versions of Ubuntu on which Beckn ONIX has been tested and confirmed to work. Specifically, the verified versions 22.04 and 20.04 need to be mentioned in the guide as pre-requisites. Additionally, it should be checked if Beckn ONIX works with Ubuntu version 24.04.

### Goals
- [x] Document Ubuntu versions 22.04 and 20.04 as verified pre-requisites for Beckn ONIX in the guide.
- [x] Verify if Beckn ONIX works with Ubuntu version 24.04.
- [x] Update the guide with findings from the verification process for Ubuntu 24.04.

### Expected Outcome
The guide for Beckn ONIX will be updated to include Ubuntu versions 22.04 and 20.04 as pre-requisites. Verification results for Ubuntu version 24.04 will be documented, and the guide will be updated accordingly.

### Acceptance Criteria
- [x] Ubuntu versions 22.04 and 20.04 are documented as pre-requisites in the guide.
- [x] Verification process for Ubuntu version 24.04 is completed.
- [x] Guide is updated with the findings from the verification of Ubuntu 24.04.

### Mockups / Wireframes
Not applicable

### Product Name
Beckn 

### Domain
Beckn ONIX

### Tech Skills Needed
- Beckn ONIX 
- Ubuntu Administration
- Documentation

### Complexity
Low

### Category
Infrastructure

### Sub Category
Documentation and Verification

**Comment by prasad-takale-eminds** [comment]
We have updated the Document with supported OS details. 
PR: https://github.com/beckn/beckn-onix/pull/190

**Comment by emmayank** [comment]
**Review Completed** 

@prasad-takale-eminds  please merge the PR as @vbabuEM  has already approved it

**Comment by yesrag2309** [comment]
@emmayank - As we discussed in today sync up call, if the PR is merged please update the card and take it closure.

@viraj89 @faizmagic
